-- Run only on an isolated PostgreSQL database after the migration.
begin;
truncate public.youtube_live_api_cache, public.youtube_live_api_attempts;
do $$
declare a jsonb; b jsonb; lease uuid; key text := repeat('a',64); old_payload jsonb;
begin
  if has_sequence_privilege('anon','public.youtube_live_api_attempts_id_seq','USAGE') or has_sequence_privilege('authenticated','public.youtube_live_api_attempts_id_seq','USAGE') or has_table_privilege('anon','public.youtube_live_api_cache','SELECT') or has_table_privilege('authenticated','public.youtube_live_api_attempts','INSERT') or has_function_privilege('anon','public.youtube_claim_live_api(text,text)','EXECUTE') or has_function_privilege('authenticated','public.youtube_finish_live_api(text,uuid,jsonb)','EXECUTE') then raise exception 'Public cache access'; end if;
  a := public.youtube_claim_live_api(key,'search');
  if a->>'state' <> 'claimed' then raise exception 'First claim failed'; end if;
  lease := (a->>'leaseId')::uuid;
  b := public.youtube_claim_live_api(key,'search');
  if b->>'state' <> 'unavailable' or (select count(*) from public.youtube_live_api_attempts) <> 1 then raise exception 'Duplicate consumed quota'; end if;
  if public.youtube_finish_live_api(key,gen_random_uuid(),'{"items":[]}') then raise exception 'Foreign lease accepted'; end if;
  if not public.youtube_finish_live_api(key,lease,'{"items":[]}') then raise exception 'Finish failed'; end if;
  a := public.youtube_claim_live_api(key,'search');
  if (select fetched_at from public.youtube_live_api_cache where cache_key=key) is null then raise exception 'Missing DB proof'; end if;
  if a->>'state' <> 'cached' or a->'payload' <> '{"items":[]}'::jsonb then raise exception 'Cache miss'; end if;
  old_payload := a;
  b := public.youtube_claim_live_api(key,'search');
  if b->>'fetchedAt' <> old_payload->>'fetchedAt' then raise exception 'Proof timestamp changed'; end if;
  update public.youtube_live_api_cache set fetched_at=clock_timestamp()-interval '61 minutes' where cache_key=key;
  a := public.youtube_claim_live_api(key,'search'); lease := (a->>'leaseId')::uuid;
  update public.youtube_live_api_cache set lease_until=clock_timestamp()-interval '1 second' where cache_key=key;
  if public.youtube_finish_live_api(key,lease,'{"items":[]}') then raise exception 'Expired lease accepted'; end if;
  a := public.youtube_claim_live_api(key,'search');
  if a->>'state' <> 'claimed' or (a->>'leaseId')::uuid = lease then raise exception 'Lease recovery failed'; end if;
  if public.youtube_finish_live_api(key,lease,'{"items":[]}') then raise exception 'Old lease overwrote renewed lease'; end if;
  if not public.youtube_finish_live_api(key,(a->>'leaseId')::uuid,null) then raise exception 'Failure finish failed'; end if;
  b := public.youtube_claim_live_api(key,'search');
  if b->>'state' <> 'unavailable' then raise exception 'Backoff missing'; end if;
  if (select payload from public.youtube_live_api_cache where cache_key=key) <> '{"items":[]}'::jsonb then raise exception 'Failure destroyed cache'; end if;
  truncate public.youtube_live_api_attempts;
  insert into public.youtube_live_api_attempts(bucket) select 'search' from generate_series(1,96);
  a := public.youtube_claim_live_api(repeat('b',64),'search');
  if a->>'state' <> 'unavailable' or (select count(*) from public.youtube_live_api_attempts) <> 96 then raise exception 'Search quota exceeded'; end if;
  a := public.youtube_claim_live_api(repeat('c',64),'videos');
  if a->>'state' <> 'claimed' then raise exception 'Buckets improperly coupled'; end if;
  insert into public.youtube_live_api_attempts(bucket) select 'general' from generate_series(1,8999);
  a := public.youtube_claim_live_api(repeat('d',64),'channels');
  if a->>'state' <> 'unavailable' then raise exception 'General quota exceeded'; end if;
  update public.youtube_live_api_attempts set requested_at=clock_timestamp()-interval '25 hours';
  a := public.youtube_claim_live_api(repeat('d',64),'channels');
  if a->>'state' <> 'claimed' or (select count(*) from public.youtube_live_api_attempts) <> 1 then raise exception 'Rolling window not pruned'; end if;
  a := public.youtube_claim_live_api(repeat('f',64),'videos');
  if not public.youtube_finish_live_api(repeat('f',64),(a->>'leaseId')::uuid,'{"items":[]}') then raise exception 'Video write failed'; end if;
  if (select fetched_at from public.youtube_live_api_cache where cache_key=repeat('f',64)) <> (a->>'fetchedAt')::timestamptz then raise exception 'Claim proof origin changed'; end if;
  update public.youtube_live_api_cache set fetched_at=clock_timestamp()-interval '179 seconds' where cache_key=repeat('f',64);
  if public.youtube_claim_live_api(repeat('f',64),'videos')->>'state' <> 'cached' then raise exception 'Video TTL too short'; end if;
  update public.youtube_live_api_cache set fetched_at=clock_timestamp()-interval '180 seconds' where cache_key=repeat('f',64);
  if public.youtube_claim_live_api(repeat('f',64),'videos')->>'state' <> 'claimed' then raise exception 'Video TTL too long'; end if;
  raise notice 'YouTube cache ACL, lease, freshness, failure, recovery, both budgets and rolling expiry passed';
end $$;
set local role service_role;
select public.youtube_claim_live_api(repeat('9',64),'channels')->>'state' as service_role_claim;
rollback;
