import "server-only";
import { z } from "zod";
import { fulfillmentStatusSchema } from "../../features/benefit/domain/fulfillment";
import { AuthError } from "../../features/auth/domain/auth-errors";
import type { AdminSession } from "../admin/admin-session-gate";
import { adminCorrelationId } from "./blockchain-job-route";
import type { BenefitFulfillmentAdminRepository } from "./benefit-fulfillment-admin-repository";
export interface BenefitFulfillmentAdminRouteDependencies{authorize(input:{authorization:string;correlationId:string}):Promise<AdminSession>;repository:BenefitFulfillmentAdminRepository;}
const body=z.object({expectedRevision:z.number().int().positive(),toStatus:fulfillmentStatusSchema,carrier:z.string().trim().min(1).max(100).optional(),trackingNumber:z.string().trim().min(1).max(200).optional(),operatorMemo:z.string().trim().min(10).max(1000)}).strict();
const json=(value:unknown,status:number)=>Response.json(value,{status,headers:{"cache-control":"private, no-store",vary:"Authorization"}});
async function auth(request:Request,d:BenefitFulfillmentAdminRouteDependencies,c:string){try{return await d.authorize({authorization:request.headers.get("authorization")??"",correlationId:c});}catch(e){if(e instanceof AuthError)return json({error:{code:e.status===401?"UNAUTHENTICATED":"FORBIDDEN"}},e.status);return json({error:{code:"FULFILLMENT_UNAVAILABLE"}},503);}}
export function createGetBenefitWinnerHandler(d:BenefitFulfillmentAdminRouteDependencies){return async(request:Request,input:{winnerId:string})=>{const c=adminCorrelationId(request),a=await auth(request,d,c);if(a instanceof Response)return a;const reveal=new URL(request.url).searchParams.get("reveal")==="true";if(reveal&&a.role==="viewer")return json({error:{code:"FORBIDDEN"}},403);try{return json(await d.repository.read({actor:{appUserId:a.appUserId,allowlistId:a.allowlistId},correlationId:c,winnerId:input.winnerId,reveal}),200);}catch{return json({error:{code:"FULFILLMENT_UNAVAILABLE"}},503);}};}
export function createPostBenefitWinnerHandler(d:BenefitFulfillmentAdminRouteDependencies){return async(request:Request,input:{winnerId:string})=>{const c=adminCorrelationId(request),a=await auth(request,d,c);if(a instanceof Response)return a;if(a.role==="viewer")return json({error:{code:"FORBIDDEN"}},403);let p;try{p=body.parse(await request.json());}catch{return json({error:{code:"INVALID_REQUEST"}},400);}try{return json(await d.repository.transition({actor:{appUserId:a.appUserId,allowlistId:a.allowlistId},correlationId:c,winnerId:input.winnerId,...p}),200);}catch(e){return json({error:{code:/TRANSITION|REVISION|TRACKING|MEMO/.test(e instanceof Error?e.message:"")?"FULFILLMENT_REJECTED":"FULFILLMENT_UNAVAILABLE"}},/TRANSITION|REVISION|TRACKING|MEMO/.test(e instanceof Error?e.message:"")?409:503);}};}
