export const actionCodes = {
  FAN_VERIFIED: 1,
  LIVE_RESERVED: 2,
  LIVE_ATTENDED: 3,
  MISSION_COMPLETED: 4,
  SURVEY_SUBMITTED: 5,
  FIRST_REACTION: 6,
  WELCOME_COMPLETED: 7,
  FIRST_COMMENT: 8,
  INVITE_COMPLETED: 9,
  DAILY_CHECKIN: 10,
  COLLECTIBLE_CLAIMED: 11,
} as const;

export const linkOrigins = { MINTED_NOW: 0, LINKED_EXISTING: 1 } as const;
