export const avatarEditorCopy = {
  ko: {
    avatar: "프로필 이미지",
    help: "캐릭터를 고르거나 내 사진을 사용할 수 있어요.",
    change: "변경",
    loading: "프로필 이미지를 불러오는 중",
    loadError: "프로필 이미지를 불러오지 못했어요.",
    retry: "다시 시도",
    dialogTitle: "프로필 이미지 변경",
    dialogHelp: "캐릭터 또는 사진을 선택한 뒤 저장해 주세요.",
    characters: "캐릭터 선택",
    choosePhoto: "사진 업로드",
    replacePhoto: "다른 사진 선택",
    photoHelp: "JPEG, PNG, WebP · 최대 4MB",
    crop: "사진 위치 조정",
    cropHelp: "사진을 드래그하거나 방향키로 위치를 맞추세요.",
    zoom: "확대",
    deletePhoto: "사진 삭제",
    cancel: "취소",
    save: "저장",
    saving: "저장 중…",
    invalidType: "JPEG, PNG 또는 WebP 파일을 선택해 주세요.",
    tooLarge: "4MB 이하의 사진을 선택해 주세요.",
    decodeFailed: "사진을 열지 못했어요. 다른 파일을 선택해 주세요.",
    failed: "저장하지 못했어요. 선택한 내용을 유지했으니 다시 시도해 주세요.",
    conflict: "다른 곳에서 프로필 이미지가 변경됐어요. 최신 상태를 확인한 뒤 다시 저장해 주세요.",
    refreshFailed: "최신 상태를 불러오지 못했어요. 연결을 확인하고 다시 불러와 주세요.",
    refresh: "최신 상태 다시 불러오기",
    photoAlt: "조정할 프로필 사진",
  },
  en: {
    avatar: "Profile image",
    help: "Choose a character or use your own photo.",
    change: "Change",
    loading: "Loading profile image",
    loadError: "We couldn't load your profile image.",
    retry: "Try again",
    dialogTitle: "Change profile image",
    dialogHelp: "Choose a character or photo, then save.",
    characters: "Choose a character",
    choosePhoto: "Upload photo",
    replacePhoto: "Choose another photo",
    photoHelp: "JPEG, PNG, WebP · up to 4MB",
    crop: "Adjust photo",
    cropHelp: "Drag the photo or use the arrow keys to position it.",
    zoom: "Zoom",
    deletePhoto: "Delete photo",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving…",
    invalidType: "Choose a JPEG, PNG, or WebP file.",
    tooLarge: "Choose a photo up to 4MB.",
    decodeFailed: "We couldn't open that photo. Choose another file.",
    failed: "We couldn't save it. Your selection is still here, so try again.",
    conflict: "Your profile image changed elsewhere. Review the latest version, then save again.",
    refreshFailed: "We couldn't load the latest version. Check your connection and try again.",
    refresh: "Reload latest version",
    photoAlt: "Profile photo being adjusted",
  },
} as const;
