import path from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";
const here = path.dirname(fileURLToPath(import.meta.url));
const web = path.resolve(here, "../..");
const ids = Array.from({ length: 24 }, (_, index) => `${String(index + 1).padStart(8, "0")}-1111-4111-8111-${String(index + 1).padStart(12, "0")}`);
const actions = ["verification","reaction","checkin","comment","membership_instagram","membership_tiktok","membership_youtube","share"].map((key, index) => ({ key, amount: 1, status: ["awarded","available","awarded","processing","pending","available","awarded","pending"][index], href: key === "verification" ? "/c/elina/verify" : key === "checkin" ? "/elina#daily-checkin" : key.startsWith("membership") ? "/elina?tab=certifications#celebrity-content" : "/elina" }));
const rows = ids.map((id, index) => ({ id, sequence: 24 - index, sourceType: index % 5 === 0 ? "benefit_entry" : index % 4 === 0 ? "checkin" : "verification", label: index % 5 === 0 ? "뱅크시 전시 티켓" : "verification", amount: index % 5 === 0 ? -1 : 1, createdAt: `2026-09-${String(15 - Math.min(index, 14)).padStart(2, "0")}T01:00:00.000Z`, occurredAt: `2026-09-${String(15 - Math.min(index, 14)).padStart(2, "0")}T00:30:00.000Z`, backfill: index === 1, balance: Math.max(0, 8 - index) }));
function ticketsApi(port) { return (req,res,next)=>{ if(!req.url?.startsWith('/api/me/tickets')) return next(); const url=new URL(req.url,`http://127.0.0.1:${port}`); const scenario=url.searchParams.get('scenario')??new URLSearchParams(req.headers.referer?.split('?')[1]??'').get('scenario'); if(scenario==='error'){res.statusCode=503;res.end('{}');return;} const send=()=>{const before=url.searchParams.get('before');const page=before?rows.slice(20):rows.slice(0,20);res.setHeader('content-type','application/json');res.end(JSON.stringify({enabled:true,creator:{slug:'elina',name:url.searchParams.get('locale')==='en'?'Elina':'엘리나'},balance:8,today:'2026-09-15',actions,history:page,nextBefore:before?null:'5'}));}; if(scenario==='loading')setTimeout(send,3000);else send(); }; }
export async function startHarness({ port = 4197 } = {}) {
  const server = await createServer({ configFile:false, esbuild:{jsx:"automatic"}, plugins:[{name:"tickets-local-api",configureServer(dev){dev.middlewares.use(ticketsApi(port));}}], root:here, publicDir:path.join(web,"public"), cacheDir:path.join(web,"node_modules/.vite-tickets-local"), resolve:{alias:[{find:"@",replacement:web},...['next/link','next/image','next/navigation','server-only'].map(name=>({find:name,replacement:path.join(web,"e2e/mission-local",{'next/link':'next-link.tsx','next/image':'next-image.tsx','next/navigation':'next-navigation.ts','server-only':'server-only.ts'}[name])})),{find:"@privy-io/react-auth",replacement:path.join(here,"privy.ts")}]}, server:{host:"127.0.0.1",port,strictPort:true,fs:{allow:[web,path.resolve(web,"../../node_modules")]}}, define:{"process.env.NEXT_PUBLIC_APP_URL":JSON.stringify(`http://localhost:${port}`)} });
  await server.listen(); return {baseURL:`http://127.0.0.1:${port}`,close:()=>server.close()};
}
if (process.argv[1] === fileURLToPath(import.meta.url)) { const harness=await startHarness(); console.log(harness.baseURL); }
