import {beforeEach,describe,expect,it,vi} from "vitest";
vi.mock("server-only",()=>({}));
import {createInstagramOwnerCallbackHandler,createInstagramOwnerConfirmHandler,createInstagramOwnerPendingHandler,createInstagramOwnerStartHandler,type InstagramOwnerDependencies} from "./owner-routes";
import {secretHash} from "./crypto";

const origin="https://byus.test",actor="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1",celebrity="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbb1",generation="cccccccc-cccc-4ccc-8ccc-ccccccccccc1";
const state="s".repeat(43),browser="b".repeat(43),pending="p".repeat(43);
const account={celebrityId:celebrity,slug:"creator",name:"크리에이터",username:"creator",avatarUrl:"/creator.webp",generation,liveEnabled:true,needsReconnect:false,mediaStatus:"syncing" as const};
function setup(){
 const ownerRepository={transition:vi.fn(async(operation:string)=>operation==="peek_pending"?{celebrity_id:celebrity,generation,locale:"ko" as const,account}:{locale:"ko" as const}),accounts:vi.fn(async()=>[account]),settings:vi.fn(),disconnect:vi.fn(),expire:vi.fn()};
 const deps={config:{origin,redirectUri:`${origin}/connect/instagram/callback`},provider:{authorizationUrl:vi.fn((s:string)=>`https://instagram.test/oauth?state=${s}`)},ownerRepository,ownerService:{callback:vi.fn(async()=>pending),disconnect:vi.fn()},authorizeFan:vi.fn(async()=>({appUserId:actor}))} as unknown as InstagramOwnerDependencies;
 return {deps,ownerRepository};
}
const cookies=`__Host-byus_ig_owner_browser=${browser}; __Host-byus_ig_owner_pending=${pending}`;
describe("Instagram creator owner API",()=>{
 beforeEach(()=>vi.clearAllMocks());
 it("authenticates before creating a state and binds it to actor and browser",async()=>{const {deps,ownerRepository}=setup();const response=await createInstagramOwnerStartHandler(deps)(new Request(`${origin}/api/me/instagram/start`,{method:"POST",headers:{authorization:"Bearer fresh","content-type":"application/json"},body:'{"locale":"ko"}'}));expect(response.status).toBe(200);expect(deps.authorizeFan).toHaveBeenCalled();expect(ownerRepository.transition).toHaveBeenCalledWith("start",expect.stringMatching(/^[a-f0-9]{64}$/),actor,expect.stringMatching(/^[a-f0-9]{64}$/),{locale:"ko"});expect(response.headers.get("set-cookie")).toContain("HttpOnly");const body=await response.json();expect(new URL(body.authorizationUrl).searchParams.get("state")).toMatch(/^owner\.[A-Za-z0-9_-]{43}$/);});
 it("requires a fresh bearer and both cookies for pending and confirm",async()=>{const {deps,ownerRepository}=setup();deps.authorizeFan=vi.fn(async()=>{throw Object.assign(new Error("Authentication is required"),{status:401});});const unauthorized=await createInstagramOwnerPendingHandler(deps)(new Request(`${origin}/api/me/instagram/pending`,{headers:{cookie:cookies}}));expect(unauthorized.status).toBe(401);expect(ownerRepository.transition).not.toHaveBeenCalled();deps.authorizeFan=vi.fn(async()=>({appUserId:actor}));const missing=await createInstagramOwnerConfirmHandler(deps)(new Request(`${origin}/api/me/instagram/confirm`,{method:"POST",headers:{authorization:"Bearer fresh","content-type":"application/json"},body:'{"action":"confirm"}'}));expect(missing.status).toBe(409);expect(ownerRepository.transition).not.toHaveBeenCalled();});
 it("passes actor and browser hashes to pending confirmation without exposing flow secrets",async()=>{const {deps,ownerRepository}=setup();const response=await createInstagramOwnerConfirmHandler(deps)(new Request(`${origin}/api/me/instagram/confirm`,{method:"POST",headers:{authorization:"Bearer fresh",cookie:cookies,"content-type":"application/json"},body:'{"action":"confirm"}'}));expect(response.status).toBe(200);expect(ownerRepository.transition).toHaveBeenNthCalledWith(1,"peek_pending",secretHash(pending),actor,secretHash(browser));expect(ownerRepository.transition).toHaveBeenNthCalledWith(2,"confirm",secretHash(pending),actor,secretHash(browser));expect(JSON.stringify(await response.json())).not.toContain(pending);});
 it("dispatches owner callback to a clean redirect and clears browser state on cancellation",async()=>{const {deps,ownerRepository}=setup();const response=await createInstagramOwnerCallbackHandler(deps)(new Request(`${origin}/connect/instagram/callback?state=owner.${state}&error=access_denied`,{headers:{cookie:cookies}}));expect(response.status).toBe(303);expect(response.headers.get("location")).toBe("/connect/instagram?error=CANCELLED&locale=ko");expect(response.headers.get("set-cookie")).toContain("Max-Age=0");expect(ownerRepository.transition.mock.calls.map(c=>c[0])).toEqual(["peek_state","consume","cancel"]);expect(response.headers.get("location")).not.toContain(state);});
 it("returns only a stable error code when repository details contain ciphertext-like text",async()=>{const {deps,ownerRepository}=setup();ownerRepository.transition.mockRejectedValue(new Error("Instagram owner storage unavailable v1.secret.ciphertext"));const response=await createInstagramOwnerPendingHandler(deps)(new Request(`${origin}/api/me/instagram/pending`,{headers:{authorization:"Bearer fresh",cookie:cookies}}));expect(response.status).toBe(503);const text=await response.text();expect(text).toContain("INSTAGRAM_UNAVAILABLE");expect(text).not.toContain("ciphertext");});
});
