import type { AppLocale } from "@/i18n/locales";

type Copy = Record<"title" | "applications" | "rewards" | "collection" | "raffles" | "empty" | "more" | "loading" | "error" | "retry" | "login" | "back" | "submitted" | "selected" | "cancelled" | "collected" | "issued" | "score" | "activities" | "stamps" | "replyNotifications" | "officialPostNotifications" | "scheduleNotifications", string>;
export const personalCopy: Record<AppLocale, Copy> = {
  ko: { title:"내 활동 내역", applications:"신청 내역", rewards:"혜택 내역", collection:"수집 내역", raffles:"응모 내역", empty:"아직 내역이 없어요.", more:"이전 내역 더 보기", loading:"내역을 불러오는 중이에요.", error:"내역을 불러오지 못했어요.", retry:"다시 시도", login:"로그인하고 확인하기", back:"MY로 돌아가기", submitted:"신청 완료", selected:"선정 완료", cancelled:"취소됨", collected:"수집 완료", issued:"패스포트 발급일", score:"팬 점수", activities:"인증된 활동", stamps:"스탬프", replyNotifications:"댓글과 답글", officialPostNotifications:"공식 소식", scheduleNotifications:"일정 알림" },
  en: { title:"My activity history", applications:"Applications", rewards:"Rewards", collection:"Collection", raffles:"Raffle entries", empty:"No activity yet.", more:"Load earlier activity", loading:"Loading activity.", error:"Couldn't load activity.", retry:"Try again", login:"Sign in to view", back:"Back to MY", submitted:"Submitted", selected:"Selected", cancelled:"Cancelled", collected:"Collected", issued:"Passport issued", score:"Fan score", activities:"Verified activities", stamps:"Stamps", replyNotifications:"Comments and replies", officialPostNotifications:"Official updates", scheduleNotifications:"Schedule reminders" },
  ja: { title:"アクティビティ履歴", applications:"申込履歴", rewards:"特典履歴", collection:"コレクション履歴", raffles:"抽選応募履歴", empty:"まだ履歴がありません。", more:"過去の履歴を見る", loading:"履歴を読み込み中です。", error:"履歴を読み込めませんでした。", retry:"再試行", login:"ログインして確認", back:"MYに戻る", submitted:"申込済み", selected:"選出済み", cancelled:"キャンセル済み", collected:"獲得済み", issued:"パスポート発行日", score:"ファンスコア", activities:"認証済みの活動", stamps:"スタンプ", replyNotifications:"コメントと返信", officialPostNotifications:"公式のお知らせ", scheduleNotifications:"予定の通知" },
  "zh-Hans": { title:"我的活动记录", applications:"申请记录", rewards:"福利记录", collection:"收藏记录", raffles:"抽奖记录", empty:"暂无记录。", more:"加载更早记录", loading:"正在加载记录。", error:"无法加载记录。", retry:"重试", login:"登录查看", back:"返回我的", submitted:"已申请", selected:"已入选", cancelled:"已取消", collected:"已收藏", issued:"护照签发日期", score:"粉丝积分", activities:"已认证活动", stamps:"印章", replyNotifications:"评论与回复", officialPostNotifications:"官方动态", scheduleNotifications:"日程提醒" },
  "zh-Hant": { title:"我的活動紀錄", applications:"申請紀錄", rewards:"福利紀錄", collection:"收藏紀錄", raffles:"抽獎紀錄", empty:"尚無紀錄。", more:"載入更早紀錄", loading:"正在載入紀錄。", error:"無法載入紀錄。", retry:"重試", login:"登入查看", back:"返回我的", submitted:"已申請", selected:"已入選", cancelled:"已取消", collected:"已收藏", issued:"護照簽發日期", score:"粉絲積分", activities:"已認證活動", stamps:"印章", replyNotifications:"留言與回覆", officialPostNotifications:"官方動態", scheduleNotifications:"行程提醒" },
  es: { title:"Mi historial de actividad", applications:"Solicitudes", rewards:"Recompensas", collection:"Colección", raffles:"Participaciones en sorteos", empty:"Aún no hay actividad.", more:"Ver actividad anterior", loading:"Cargando actividad.", error:"No se pudo cargar la actividad.", retry:"Reintentar", login:"Inicia sesión para ver", back:"Volver a MY", submitted:"Enviada", selected:"Seleccionada", cancelled:"Cancelada", collected:"Obtenida", issued:"Pasaporte emitido", score:"Puntos de fan", activities:"Actividades verificadas", stamps:"Sellos", replyNotifications:"Comentarios y respuestas", officialPostNotifications:"Novedades oficiales", scheduleNotifications:"Recordatorios de eventos" },
  id: { title:"Riwayat aktivitas saya", applications:"Pendaftaran", rewards:"Hadiah", collection:"Koleksi", raffles:"Riwayat undian", empty:"Belum ada aktivitas.", more:"Lihat aktivitas sebelumnya", loading:"Memuat aktivitas.", error:"Aktivitas gagal dimuat.", retry:"Coba lagi", login:"Masuk untuk melihat", back:"Kembali ke MY", submitted:"Terkirim", selected:"Terpilih", cancelled:"Dibatalkan", collected:"Dikoleksi", issued:"Paspor diterbitkan", score:"Poin penggemar", activities:"Aktivitas terverifikasi", stamps:"Stempel", replyNotifications:"Komentar dan balasan", officialPostNotifications:"Kabar resmi", scheduleNotifications:"Pengingat jadwal" },
  vi: { title:"Lịch sử hoạt động của tôi", applications:"Đăng ký", rewards:"Phần thưởng", collection:"Bộ sưu tập", raffles:"Lượt dự thưởng", empty:"Chưa có hoạt động.", more:"Xem hoạt động trước", loading:"Đang tải hoạt động.", error:"Không thể tải hoạt động.", retry:"Thử lại", login:"Đăng nhập để xem", back:"Quay lại MY", submitted:"Đã gửi", selected:"Đã được chọn", cancelled:"Đã hủy", collected:"Đã thu thập", issued:"Ngày cấp hộ chiếu", score:"Điểm người hâm mộ", activities:"Hoạt động đã xác thực", stamps:"Dấu", replyNotifications:"Bình luận và trả lời", officialPostNotifications:"Tin chính thức", scheduleNotifications:"Nhắc lịch" },
  th: { title:"ประวัติกิจกรรมของฉัน", applications:"การสมัคร", rewards:"รางวัล", collection:"คอลเลกชัน", raffles:"การร่วมจับรางวัล", empty:"ยังไม่มีประวัติกิจกรรม", more:"ดูกิจกรรมก่อนหน้า", loading:"กำลังโหลดกิจกรรม", error:"โหลดกิจกรรมไม่ได้", retry:"ลองอีกครั้ง", login:"เข้าสู่ระบบเพื่อดู", back:"กลับไป MY", submitted:"ส่งแล้ว", selected:"ได้รับเลือก", cancelled:"ยกเลิกแล้ว", collected:"สะสมแล้ว", issued:"วันที่ออกพาสปอร์ต", score:"คะแนนแฟน", activities:"กิจกรรมที่ยืนยันแล้ว", stamps:"แสตมป์", replyNotifications:"ความคิดเห็นและการตอบกลับ", officialPostNotifications:"ข่าวสารทางการ", scheduleNotifications:"การแจ้งเตือนกำหนดการ" },
  pt: { title:"Meu histórico de atividades", applications:"Inscrições", rewards:"Recompensas", collection:"Coleção", raffles:"Participações em sorteios", empty:"Ainda não há atividades.", more:"Ver atividades anteriores", loading:"Carregando atividades.", error:"Não foi possível carregar as atividades.", retry:"Tentar novamente", login:"Entre para ver", back:"Voltar para MY", submitted:"Enviada", selected:"Selecionada", cancelled:"Cancelada", collected:"Obtida", issued:"Passaporte emitido", score:"Pontos de fã", activities:"Atividades verificadas", stamps:"Selos", replyNotifications:"Comentários e respostas", officialPostNotifications:"Novidades oficiais", scheduleNotifications:"Lembretes de eventos" },
  fr: { title:"Mon historique d’activité", applications:"Candidatures", rewards:"Récompenses", collection:"Collection", raffles:"Participations aux tirages", empty:"Aucune activité pour le moment.", more:"Voir les activités précédentes", loading:"Chargement des activités.", error:"Impossible de charger les activités.", retry:"Réessayer", login:"Se connecter pour voir", back:"Retour à MY", submitted:"Envoyée", selected:"Sélectionnée", cancelled:"Annulée", collected:"Obtenue", issued:"Passeport délivré", score:"Points de fan", activities:"Activités vérifiées", stamps:"Tampons", replyNotifications:"Commentaires et réponses", officialPostNotifications:"Actualités officielles", scheduleNotifications:"Rappels d’événements" },
};
