import type { AppLocale } from "../locales";

type FeedCopy = { feed: string; fanBoard: string; all: string; official: string; fans: string; intro: string; filters: string; sourceError: string; cursorExpired: string; refresh: string; readPost: string; removeFilter: string };
const copies: Record<AppLocale, FeedCopy> = {
  ko: { feed: "피드", fanBoard: "팬게시판", all: "전체", official: "최애 공식", fans: "팬 글", intro: "최애의 소식과 팬들의 이야기를 함께 나눠요.", filters: "글 종류", sourceError: "CHZZK 소식을 불러오지 못했어요. 다른 글은 계속 볼 수 있어요.", cursorExpired: "새로운 글이 있어요. 최신 피드를 다시 불러와 주세요.", refresh: "최신 피드 보기", readPost: "글 전체 보기", removeFilter: "세부 필터 해제" },
  en: { feed: "Feed", fanBoard: "Fan board", all: "All", official: "Official", fans: "Fan posts", intro: "Updates from your favorite, and stories from fellow fans.", filters: "Post type", sourceError: "CHZZK updates couldn’t load. Other posts are still available.", cursorExpired: "The feed has changed. Reload the latest posts to continue.", refresh: "Latest posts", readPost: "Read full post", removeFilter: "Clear topic filter" },
  ja: { feed: "フィード", fanBoard: "ファン掲示板", all: "すべて", official: "公式", fans: "ファンの投稿", intro: "推しの最新情報も、ファンの声もここで。", filters: "投稿の種類", sourceError: "CHZZKの情報を読み込めませんでした。ほかの投稿は引き続きご覧いただけます。", cursorExpired: "投稿が更新されました。最新のフィードを読み込んでください。", refresh: "最新の投稿を見る", readPost: "投稿をすべて読む", removeFilter: "詳細フィルターを解除" },
  "zh-Hans": { feed: "动态", fanBoard: "粉丝社区", all: "全部", official: "官方动态", fans: "粉丝帖子", intro: "一起分享偶像的动态和粉丝的故事。", filters: "帖子类型", sourceError: "暂时无法加载CHZZK动态，其他帖子仍可浏览。", cursorExpired: "动态已更新，请重新加载最新帖子。", refresh: "查看最新帖子", readPost: "查看全文", removeFilter: "清除详细筛选" },
  "zh-Hant": { feed: "動態", fanBoard: "粉絲社群", all: "全部", official: "官方動態", fans: "粉絲貼文", intro: "一起分享偶像的動態與粉絲的故事。", filters: "貼文類型", sourceError: "暫時無法載入CHZZK動態，其他貼文仍可瀏覽。", cursorExpired: "動態已更新，請重新載入最新貼文。", refresh: "查看最新貼文", readPost: "查看全文", removeFilter: "清除詳細篩選" },
  es: { feed: "Publicaciones", fanBoard: "Comunidad de fans", all: "Todo", official: "Oficial", fans: "Fans", intro: "Novedades de tu artista y momentos que comparten sus fans.", filters: "Tipo de publicación", sourceError: "No se pudieron cargar las novedades de CHZZK. Las demás publicaciones siguen disponibles.", cursorExpired: "Hay cambios en las publicaciones. Carga las más recientes para continuar.", refresh: "Ver lo más reciente", readPost: "Leer publicación completa", removeFilter: "Quitar filtro de tema" },
  id: { feed: "Feed", fanBoard: "Komunitas penggemar", all: "Semua", official: "Resmi", fans: "Penggemar", intro: "Kabar dari idola dan cerita dari sesama penggemar.", filters: "Jenis postingan", sourceError: "Kabar CHZZK belum dapat dimuat. Postingan lain tetap tersedia.", cursorExpired: "Feed telah berubah. Muat postingan terbaru untuk melanjutkan.", refresh: "Lihat postingan terbaru", readPost: "Baca selengkapnya", removeFilter: "Hapus filter topik" },
  vi: { feed: "Bảng tin", fanBoard: "Cộng đồng người hâm mộ", all: "Tất cả", official: "Chính thức", fans: "Người hâm mộ", intro: "Cùng chia sẻ tin từ thần tượng và câu chuyện của người hâm mộ.", filters: "Loại bài viết", sourceError: "Không tải được tin CHZZK. Bạn vẫn có thể xem các bài viết khác.", cursorExpired: "Bảng tin đã thay đổi. Hãy tải lại các bài viết mới nhất.", refresh: "Xem bài viết mới nhất", readPost: "Đọc toàn bộ bài viết", removeFilter: "Bỏ bộ lọc chủ đề" },
  th: { feed: "ฟีด", fanBoard: "ชุมชนแฟนคลับ", all: "ทั้งหมด", official: "ทางการ", fans: "โพสต์จากแฟน", intro: "แบ่งปันข่าวจากศิลปินที่ชอบและเรื่องราวจากแฟน ๆ", filters: "ประเภทโพสต์", sourceError: "โหลดข่าวจาก CHZZK ไม่สำเร็จ แต่ยังดูโพสต์อื่นได้", cursorExpired: "ฟีดมีการเปลี่ยนแปลง กรุณาโหลดโพสต์ล่าสุดอีกครั้ง", refresh: "ดูโพสต์ล่าสุด", readPost: "อ่านโพสต์ทั้งหมด", removeFilter: "ล้างตัวกรองหัวข้อ" },
  pt: { feed: "Publicações", fanBoard: "Comunidade de fãs", all: "Tudo", official: "Oficial", fans: "Fãs", intro: "Novidades do seu artista e histórias de outros fãs.", filters: "Tipo de publicação", sourceError: "Não foi possível carregar o CHZZK. As outras publicações continuam disponíveis.", cursorExpired: "As publicações mudaram. Carregue as mais recentes para continuar.", refresh: "Ver mais recentes", readPost: "Ler publicação completa", removeFilter: "Remover filtro de assunto" },
  fr: { feed: "Fil", fanBoard: "Communauté de fans", all: "Tout", official: "Officiel", fans: "Fans", intro: "Les nouvelles de votre artiste et les histoires de ses fans.", filters: "Type de publication", sourceError: "Les nouvelles CHZZK sont indisponibles. Les autres publications restent accessibles.", cursorExpired: "Le fil a changé. Rechargez les dernières publications pour continuer.", refresh: "Voir les dernières publications", readPost: "Lire la publication", removeFilter: "Retirer le filtre de sujet" },
};
export function feedCopy(locale: AppLocale): FeedCopy { return copies[locale]; }
