import type { AppLocale } from "../locales";

const copy = {
  ko: ["커뮤니티", "현장에서 담은 사진부터 최애에게 전하고 싶은 이야기까지. 팬들과 함께 나눠요.", "최애 선택", "팬 게시판", "함께하는 팬", "찐팬 인증", "팬 요청", "팬페이지", "최근 함께한 팬", "좋아요와 패스포트로 모인 팬들이에요.", "아직 함께하는 팬이 없어요. 첫 이야기를 남겨 보세요.", "공유할 순간이 있나요?", "직접 찍은 현장 사진과 짤, 후기를 올려 보세요. 사진은 한 번에 4장까지 담을 수 있어요.", "팬 활동을 인증하고 기록으로 남겨요.", "참여할 커뮤니티를 준비하고 있어요.", "명"],
  en: ["Community", "From photos you took at the venue to stories about your favorite. Share them with fellow fans.", "Choose a favorite", "Fan posts", "Fans", "Fan verification", "Fan requests", "Fan page", "Recently joined fans", "Fans who joined with a like or a Passport.", "No fans here yet. Start the first conversation.", "Have a moment to share?", "Share your own event photos, memes and stories. Add up to 4 photos per post.", "Verify your fan activities and keep a record.", "Communities are being prepared.", " fans"],
  ja: ["コミュニティ", "現場で撮った写真も、推しへの想いも。ファン同士でシェアしましょう。", "推しを選択", "ファン掲示板", "ファン", "ファン認証", "ファンのリクエスト", "ファンページ", "最近参加したファン", "いいねやパスポートで集まったファンです。", "まだファンがいません。最初の投稿をしてみましょう。", "シェアしたい瞬間は？", "自分で撮った現場写真やミーム、感想を投稿しましょう。写真は1投稿につき4枚まで。", "ファン活動を認証して記録しましょう。", "コミュニティを準備しています。", "人"],
  "zh-Hans": ["社区", "从现场拍摄的照片到关于偶像的故事，与粉丝们一起分享。", "选择艺人", "粉丝帖子", "粉丝", "真爱粉认证", "粉丝请求", "粉丝主页", "最近加入的粉丝", "通过点赞或护照聚集的粉丝。", "还没有粉丝。来发布第一条内容吧。", "有想分享的瞬间吗？", "分享自己拍摄的现场照片、表情包和感想。每篇最多4张照片。", "认证并记录你的粉丝活动。", "社区正在筹备中。", "人"],
  "zh-Hant": ["社群", "從現場拍攝的照片到關於偶像的故事，與粉絲們一起分享。", "選擇藝人", "粉絲貼文", "粉絲", "真愛粉認證", "粉絲請求", "粉絲主頁", "最近加入的粉絲", "透過按讚或護照聚集的粉絲。", "還沒有粉絲。來發表第一篇貼文吧。", "有想分享的瞬間嗎？", "分享自己拍攝的現場照片、迷因和感想。每篇最多4張照片。", "認證並記錄你的粉絲活動。", "社群正在籌備中。", "人"],
  es: ["Comunidad", "Comparte tus fotos de eventos e historias de tu artista favorito con otros fans.", "Elige un favorito", "Publicaciones", "Fans", "Verificación de fan", "Solicitudes", "Página de fans", "Fans recientes", "Fans que se unieron con un me gusta o un Passport.", "Aún no hay fans. Inicia la conversación.", "¿Un momento para compartir?", "Publica tus fotos de eventos, memes y experiencias. Hasta 4 fotos por publicación.", "Verifica tus actividades y guarda un recuerdo.", "Estamos preparando las comunidades.", " fans"],
  id: ["Komunitas", "Bagikan foto dari lokasi acara dan cerita tentang favoritmu bersama penggemar lain.", "Pilih favorit", "Kiriman penggemar", "Penggemar", "Verifikasi penggemar", "Permintaan", "Halaman penggemar", "Penggemar terbaru", "Penggemar yang bergabung lewat suka atau Passport.", "Belum ada penggemar. Mulai percakapan pertama.", "Ada momen untuk dibagikan?", "Bagikan foto acara sendiri, meme, dan cerita. Maksimal 4 foto per kiriman.", "Verifikasi dan catat aktivitas penggemarmu.", "Komunitas sedang disiapkan.", " penggemar"],
  vi: ["Cộng đồng", "Chia sẻ ảnh tại sự kiện và câu chuyện về thần tượng cùng người hâm mộ.", "Chọn thần tượng", "Bài đăng", "Người hâm mộ", "Xác minh fan", "Yêu cầu", "Trang người hâm mộ", "Fan mới tham gia", "Người hâm mộ tham gia bằng lượt thích hoặc Passport.", "Chưa có người hâm mộ. Hãy bắt đầu cuộc trò chuyện.", "Có khoảnh khắc muốn chia sẻ?", "Đăng ảnh sự kiện tự chụp, meme và cảm nhận. Tối đa 4 ảnh mỗi bài.", "Xác minh và ghi lại hoạt động của bạn.", "Cộng đồng đang được chuẩn bị.", " người"],
  th: ["ชุมชน", "แบ่งปันภาพที่ถ่ายในงานและเรื่องราวของศิลปินที่ชอบกับแฟน ๆ", "เลือกศิลปิน", "โพสต์ของแฟน", "แฟน ๆ", "ยืนยันแฟนคลับ", "คำขอของแฟน", "แฟนเพจ", "แฟนที่เข้าร่วมล่าสุด", "แฟนที่เข้าร่วมผ่านการกดถูกใจหรือ Passport", "ยังไม่มีแฟน เริ่มเรื่องราวแรกกันเลย", "มีช่วงเวลาที่อยากแบ่งปันไหม?", "แชร์ภาพงานที่ถ่ายเอง มีม และความประทับใจ ได้สูงสุด 4 ภาพต่อโพสต์", "ยืนยันและบันทึกกิจกรรมแฟนคลับของคุณ", "กำลังเตรียมชุมชน", " คน"],
  pt: ["Comunidade", "Compartilhe fotos dos eventos e histórias do seu artista favorito com outros fãs.", "Escolha um favorito", "Publicações", "Fãs", "Verificação de fã", "Pedidos dos fãs", "Página de fãs", "Fãs recentes", "Fãs que chegaram com uma curtida ou um Passport.", "Ainda não há fãs. Comece a conversa.", "Um momento para compartilhar?", "Publique suas fotos de eventos, memes e relatos. Até 4 fotos por publicação.", "Verifique suas atividades e guarde um registro.", "Estamos preparando as comunidades.", " fãs"],
  fr: ["Communauté", "Partagez vos photos prises sur place et vos histoires avec les autres fans.", "Choisir un favori", "Publications", "Fans", "Vérification de fan", "Demandes des fans", "Page de fans", "Fans récents", "Des fans réunis par un J’aime ou un Passport.", "Pas encore de fans. Lancez la conversation.", "Un moment à partager ?", "Publiez vos photos d’événements, mèmes et récits. Jusqu’à 4 photos par publication.", "Vérifiez vos activités et gardez-en une trace.", "Les communautés sont en préparation.", " fans"],
} satisfies Record<AppLocale, readonly string[]>;

export function communityCopy(locale: AppLocale) {
  const [title, intro, choose, posts, fans, certifications, requests, fanpage, recentFans, fansIntro, noFans, photoTitle, photoIntro, verifyIntro, empty, countSuffix] = copy[locale];
  return { title, intro, choose, posts, fans, certifications, requests, fanpage, recentFans, fansIntro, noFans, photoTitle, photoIntro, verifyIntro, empty, countSuffix };
}
