import type { AppLocale } from "@/i18n/locales";

type Copy = { title: string; body: string; confirm: string; action: string; busy: string; failed: string; pending: string; completed: string; leave: string; logoutFailed: string };
export const accountDeletionCopy: Record<AppLocale, Copy> = {
  ko: { title: "계정 삭제", body: "계정과 프로필, 직접 올린 콘텐츠와 비공개 파일을 삭제합니다. 삭제를 요청하면 즉시 계정을 사용할 수 없습니다. 블록체인 기록과 보상 처리에 필요한 기록은 개인 정보를 제거한 뒤 보관합니다.", confirm: "계속하려면 DELETE를 입력해 주세요.", action: "계정 삭제 요청", busy: "삭제 요청 중…", failed: "삭제를 요청하지 못했어요. 다시 시도해 주세요.", pending: "삭제 요청을 접수했어요. 계정 이용은 중지되었으며, 남은 파일과 로그인 계정은 정리가 끝날 때까지 자동으로 다시 처리합니다.", completed: "계정 삭제를 완료했어요.", leave: "홈으로", logoutFailed: "로그아웃하지 못했어요. 다시 눌러 주세요." },
  en: { title: "Delete account", body: "Delete your account, profile, uploaded content and private files. Account access stops as soon as the request is accepted. Blockchain records and records needed to process rewards are retained without your personal details.", confirm: "Type DELETE to continue.", action: "Request account deletion", busy: "Requesting deletion…", failed: "Could not request deletion. Please try again.", pending: "Your deletion request was accepted. Account access has stopped. Remaining files and your sign-in account will be retried automatically until cleanup is complete.", completed: "Your account has been deleted.", leave: "Home", logoutFailed: "Could not log out. Please try again." },
  ja: { title: "アカウント削除", body: "アカウント、プロフィール、投稿したコンテンツ、非公開ファイルを削除します。申請が受け付けられると利用できなくなります。ブロックチェーン記録と特典処理に必要な記録は、個人情報を削除して保管します。", confirm: "続行するには DELETE と入力してください。", action: "削除を申請", busy: "申請中…", failed: "申請できませんでした。もう一度お試しください。", pending: "削除申請を受け付けました。利用は停止されています。残りのファイルとログインアカウントの削除は、完了するまで自動で再試行します。", completed: "アカウントを削除しました。", leave: "ホームへ", logoutFailed: "ログアウトできませんでした。もう一度お試しください。" },
  "zh-Hans": { title: "删除账号", body: "删除账号、个人资料、上传内容和私密文件。申请受理后，账号将立即停用。区块链记录和奖励处理所需的记录将在去除个人信息后保留。", confirm: "输入 DELETE 以继续。", action: "申请删除账号", busy: "正在申请…", failed: "申请失败，请重试。", pending: "已受理删除申请，账号已停用。剩余文件和登录账号将自动重试删除，直至完成。", completed: "账号已删除。", leave: "首页", logoutFailed: "退出登录失败，请重试。" },
  "zh-Hant": { title: "刪除帳號", body: "刪除帳號、個人資料、上傳內容和私人檔案。申請受理後，帳號將立即停用。區塊鏈紀錄和獎勵處理所需的紀錄將在移除個人資訊後保留。", confirm: "輸入 DELETE 以繼續。", action: "申請刪除帳號", busy: "正在申請…", failed: "申請失敗，請重試。", pending: "已受理刪除申請，帳號已停用。剩餘檔案和登入帳號將自動重試刪除，直到完成。", completed: "帳號已刪除。", leave: "首頁", logoutFailed: "登出失敗，請重試。" },
  es: { title: "Eliminar cuenta", body: "Elimina tu cuenta, perfil, contenido subido y archivos privados. El acceso se desactiva al aceptar la solicitud. Los registros de blockchain y los necesarios para gestionar recompensas se conservan sin tus datos personales.", confirm: "Escribe DELETE para continuar.", action: "Solicitar eliminación", busy: "Enviando solicitud…", failed: "No se pudo solicitar la eliminación. Inténtalo de nuevo.", pending: "Solicitud aceptada. El acceso está desactivado. Se reintentará automáticamente la eliminación de los archivos restantes y de tu cuenta de acceso hasta completarla.", completed: "Tu cuenta se ha eliminado.", leave: "Inicio", logoutFailed: "No se pudo cerrar sesión. Inténtalo de nuevo." },
  id: { title: "Hapus akun", body: "Hapus akun, profil, konten unggahan, dan file pribadi. Akses akun dihentikan setelah permintaan diterima. Catatan blockchain dan pemrosesan hadiah disimpan tanpa data pribadi Anda.", confirm: "Ketik DELETE untuk melanjutkan.", action: "Ajukan penghapusan akun", busy: "Mengirim permintaan…", failed: "Permintaan gagal. Silakan coba lagi.", pending: "Permintaan diterima dan akses akun dihentikan. Penghapusan file yang tersisa dan akun masuk akan dicoba ulang secara otomatis sampai selesai.", completed: "Akun Anda telah dihapus.", leave: "Beranda", logoutFailed: "Gagal keluar. Silakan coba lagi." },
  vi: { title: "Xóa tài khoản", body: "Xóa tài khoản, hồ sơ, nội dung đã tải lên và tệp riêng tư. Quyền truy cập sẽ dừng ngay khi yêu cầu được chấp nhận. Hồ sơ blockchain và hồ sơ cần để xử lý phần thưởng được giữ lại sau khi xóa thông tin cá nhân.", confirm: "Nhập DELETE để tiếp tục.", action: "Yêu cầu xóa tài khoản", busy: "Đang gửi yêu cầu…", failed: "Không thể gửi yêu cầu. Vui lòng thử lại.", pending: "Đã nhận yêu cầu và dừng quyền truy cập. Các tệp còn lại và tài khoản đăng nhập sẽ được tự động thử xóa lại cho đến khi hoàn tất.", completed: "Tài khoản đã được xóa.", leave: "Trang chủ", logoutFailed: "Không thể đăng xuất. Vui lòng thử lại." },
  th: { title: "ลบบัญชี", body: "ลบบัญชี โปรไฟล์ เนื้อหาที่อัปโหลด และไฟล์ส่วนตัว การเข้าถึงบัญชีจะหยุดทันทีที่รับคำขอ ข้อมูลบล็อกเชนและบันทึกที่จำเป็นต่อการจัดการรางวัลจะเก็บไว้หลังลบข้อมูลส่วนบุคคลแล้ว", confirm: "พิมพ์ DELETE เพื่อดำเนินการต่อ", action: "ขอลบบัญชี", busy: "กำลังส่งคำขอ…", failed: "ส่งคำขอไม่สำเร็จ โปรดลองอีกครั้ง", pending: "รับคำขอแล้วและหยุดการเข้าถึงบัญชี ระบบจะลองลบไฟล์ที่เหลือและบัญชีเข้าสู่ระบบใหม่โดยอัตโนมัติจนกว่าจะเสร็จ", completed: "ลบบัญชีแล้ว", leave: "หน้าหลัก", logoutFailed: "ออกจากระบบไม่สำเร็จ โปรดลองอีกครั้ง" },
  pt: { title: "Excluir conta", body: "Exclua sua conta, perfil, conteúdo enviado e arquivos privados. O acesso é interrompido assim que a solicitação é aceita. Registros de blockchain e os necessários para processar recompensas são mantidos sem seus dados pessoais.", confirm: "Digite DELETE para continuar.", action: "Solicitar exclusão", busy: "Enviando solicitação…", failed: "Não foi possível solicitar a exclusão. Tente novamente.", pending: "Solicitação aceita. O acesso foi interrompido. A exclusão dos arquivos restantes e da conta de login será repetida automaticamente até terminar.", completed: "Sua conta foi excluída.", leave: "Início", logoutFailed: "Não foi possível sair. Tente novamente." },
  fr: { title: "Supprimer le compte", body: "Supprimez votre compte, votre profil, vos contenus publiés et vos fichiers privés. L’accès cesse dès l’acceptation de la demande. Les données blockchain et les registres nécessaires aux récompenses sont conservés sans vos informations personnelles.", confirm: "Saisissez DELETE pour continuer.", action: "Demander la suppression", busy: "Envoi de la demande…", failed: "Impossible de demander la suppression. Réessayez.", pending: "Demande acceptée. L’accès est désactivé. La suppression des fichiers restants et du compte de connexion sera relancée automatiquement jusqu’à son achèvement.", completed: "Votre compte a été supprimé.", leave: "Accueil", logoutFailed: "Impossible de se déconnecter. Réessayez." },
};
