export const supportCopy = {
  ko: {
    title: "문의 내역", adminTitle: "CS 문의", intro: "궁금한 점을 남겨주세요. 답변과 이전 대화를 여기서 확인할 수 있어요.",
    adminIntro: "접수된 문의를 확인하고 답변하세요.", new: "새 문의", cancel: "취소", subject: "제목", body: "문의 내용",
    subjectHelp: "어떤 도움이 필요한지 간단히 적어주세요.", bodyHelp: "문제가 생긴 상황을 자세히 적어주세요. 비밀번호나 인증번호는 보내지 마세요.",
    submit: "문의 보내기", reply: "메시지", send: "메시지 보내기", sending: "보내는 중…", sent: "메시지를 보냈어요.",
    loading: "문의 내역을 불러오는 중이에요.", empty: "아직 남긴 문의가 없어요.", adminEmpty: "해당하는 문의가 없어요.",
    error: "문의 내역을 불러오지 못했어요.", retry: "다시 시도", refresh: "새로고침", refreshError: "최신 내용을 확인하지 못했어요. 다시 불러와 주세요.",
    loginTitle: "로그인하고 문의를 남겨주세요.", loginHelp: "내 문의와 답변을 안전하게 확인하려면 로그인이 필요해요.", login: "로그인하기",
    missing: "문의를 찾을 수 없어요.", back: "문의 목록", all: "전체", statusFilter: "문의 상태", next: "다음 문의", previous: "이전 문의",
    earlier: "이전 메시지 보기", team: "ByUs 운영팀", me: "나", fan: "문의자", resolved: "처리 완료", resolve: "처리 완료하기", resolving: "처리 중…",
    resolvedHelp: "처리 완료된 문의예요. 추가로 도움이 필요하면 메시지를 남겨주세요.", resolvedNotice: "문의를 처리 완료했어요.",
    readonly: "조회 권한으로 접속했어요. 답변과 처리 완료는 운영 권한이 필요해요.",
    invalidSubject: "제목을 1–120자로 입력해 주세요.", invalidBody: "내용을 1–4,000자로 입력해 주세요.",
    sendError: "전송을 확인하지 못했어요. 작성한 내용은 유지되니 다시 시도해 주세요.", rateError: "짧은 시간에 여러 문의를 보냈어요. 잠시 후 다시 시도해 주세요.",
    conflictError: "전송 내용을 확인하지 못했어요. 문의를 새로고침한 뒤 다시 시도해 주세요.",
    staleError: "새 메시지나 상태 변경이 있어요. 최신 내용을 확인한 뒤 처리해 주세요.",
    forbiddenError: "로그인 상태와 문의 접근 권한을 확인해 주세요.",
    status: { open: "접수", answered: "답변 완료", resolved: "처리 완료" },
  },
  en: {
    title: "My inquiries", adminTitle: "Customer support", intro: "Tell us how we can help. You can find our replies and your conversation history here.",
    adminIntro: "Review incoming inquiries and reply to customers.", new: "New inquiry", cancel: "Cancel", subject: "Subject", body: "Your inquiry",
    subjectHelp: "Briefly describe what you need help with.", bodyHelp: "Describe what happened. Do not send passwords or verification codes.",
    submit: "Send inquiry", reply: "Message", send: "Send message", sending: "Sending…", sent: "Message sent.",
    loading: "Loading inquiries…", empty: "You haven’t sent any inquiries yet.", adminEmpty: "No matching inquiries.",
    error: "We couldn’t load your inquiries.", retry: "Try again", refresh: "Refresh", refreshError: "We couldn’t check for updates. Please refresh.",
    loginTitle: "Sign in to contact us.", loginHelp: "Sign in to securely view your inquiries and our replies.", login: "Sign in",
    missing: "Inquiry not found.", back: "All inquiries", all: "All", statusFilter: "Inquiry status", next: "Next inquiries", previous: "Previous inquiries",
    earlier: "Load earlier messages", team: "ByUs support", me: "You", fan: "Customer", resolved: "Resolved", resolve: "Mark as resolved", resolving: "Resolving…",
    resolvedHelp: "This inquiry is resolved. Send another message if you still need help.", resolvedNotice: "Inquiry marked as resolved.",
    readonly: "You have read-only access. Replying and resolving inquiries require an operator role.",
    invalidSubject: "Enter a subject of 1–120 characters.", invalidBody: "Enter a message of 1–4,000 characters.",
    sendError: "We couldn’t confirm delivery. Your draft is saved here. Please try again.", rateError: "You’ve sent several inquiries recently. Please try again shortly.",
    conflictError: "We couldn’t confirm your message. Refresh the conversation before trying again.",
    staleError: "There is a new message or status update. Review the latest conversation before resolving it.",
    forbiddenError: "Check your sign-in status and permission to access this inquiry.",
    status: { open: "Received", answered: "Answered", resolved: "Resolved" },
  },
} as const;
