"use client";
import { usePrivy } from "@privy-io/react-auth";
import { useState } from "react";
import styles from "./survey-builder.module.css";
export function MissionBuilder({liveEventId}:{liveEventId:string}){
  const {getAccessToken}=usePrivy();const [type,setType]=useState<"quiz"|"survey"|"vote">("vote");const [titleKo,setTitleKo]=useState("");const [titleEn,setTitleEn]=useState("");const [questionKo,setQuestionKo]=useState("");const [questionEn,setQuestionEn]=useState("");const [options,setOptions]=useState(["",""]);const [created,setCreated]=useState("");const [message,setMessage]=useState("");
  async function command(body:unknown){const token=await getAccessToken();const response=await fetch(`/api/admin/live-events/${liveEventId}/missions`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json","x-correlation-id":crypto.randomUUID()},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error();return data as {missionId:string};}
  async function create(){try{const result=await command({command:"create",type,attendanceRequirement:"not_required",title:{ko:titleKo,en:titleEn},description:{ko:"",en:""},questions:[{position:1,text:{ko:questionKo,en:questionEn},media:null,correctPosition:type==="quiz"?1:null,options:options.map((label,index)=>({position:index+1,label:{ko:label,en:label},media:null}))}]});setCreated(result.missionId);setMessage("Mission draft created");}catch{setMessage("Mission could not be saved");}}
  async function publish(){try{await command({command:"publish",missionId:created});setMessage("Mission published");}catch{setMessage("Mission could not be published");}}
  return <main className={styles.page}><header><p>ADM · Mission Builder</p><h1>Quiz · Survey · Vote</h1></header><p role="status">{message}</p><label><span>Type</span><select value={type} onChange={e=>setType(e.target.value as typeof type)}><option value="quiz">Quiz</option><option value="survey">Survey</option><option value="vote">Vote</option></select></label><div className={styles.localeGrid}><label><span>제목</span><input value={titleKo} onChange={e=>setTitleKo(e.target.value)}/></label><label><span>Title</span><input value={titleEn} onChange={e=>setTitleEn(e.target.value)}/></label><label><span>질문</span><input value={questionKo} onChange={e=>setQuestionKo(e.target.value)}/></label><label><span>Question</span><input value={questionEn} onChange={e=>setQuestionEn(e.target.value)}/></label></div>{options.map((value,index)=><label key={index}><span>Option {index+1}</span><input value={value} onChange={e=>setOptions(current=>current.map((item,i)=>i===index?e.target.value:item))}/></label>)}<div className={styles.actions}><button type="button" onClick={()=>void create()} disabled={!titleKo||!titleEn||!questionKo||!questionEn||options.some(v=>!v)}>Create draft</button><button type="button" onClick={()=>void publish()} disabled={!created}>Publish</button></div></main>;
}
