import { createPrivyNodeAccessVerifier } from "../../../../../../server/auth/privy-node-verifier";
import { authorizeAdminSession } from "../../../../../../server/admin/admin-session-gate";
import { createSupabaseAdminSessionRepository } from "../../../../../../server/admin/supabase-admin-session-repository";
import { loadServerEnv } from "../../../../../../server/config/env";
import { createGetMissionBuilderHandler, createPostMissionBuilderHandler, createSupabaseMissionBuilderRepository } from "../../../../../../server/g5/mission-builder-route";
export const dynamic="force-dynamic";
function dependencies(){const env=loadServerEnv();const verifier=createPrivyNodeAccessVerifier({appId:env.PRIVY_APP_ID,appSecret:env.PRIVY_APP_SECRET, appEnvironment: env.PRIVY_APP_ENVIRONMENT, testAccountLoginEnabled: env.PRIVY_TEST_ACCOUNT_LOGIN_ENABLED, appleLoginEnabled: env.PRIVY_APPLE_LOGIN_ENABLED});const sessions=createSupabaseAdminSessionRepository({url:env.SUPABASE_URL,serviceRoleKey:env.SUPABASE_SERVICE_ROLE_KEY});return {repository:createSupabaseMissionBuilderRepository({url:env.SUPABASE_URL,serviceRoleKey:env.SUPABASE_SERVICE_ROLE_KEY}),authorize:({authorization,correlationId}:{authorization:string;correlationId:string})=>authorizeAdminSession({authorization,correlationId,verifier,repository:sessions})};}
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){try{return createGetMissionBuilderHandler(dependencies())(request,{liveEventId:(await params).id});}catch{return Response.json({error:{code:"MISSION_STATISTICS_UNAVAILABLE"}},{status:503});}}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){try{return createPostMissionBuilderHandler(dependencies())(request,{liveEventId:(await params).id});}catch{return Response.json({error:{code:"MISSION_BUILDER_UNAVAILABLE"}},{status:503});}}
