import { withLocalePath, type AppLocale } from "@/components/locale-path";
import type { MyReward } from "../domain/my-reward";

export const recipientCopy = {
  ko: {
    title: "수령 정보 입력",
    editTitle: "수령 정보 확인·수정",
    shippingIntro: "혜택을 받을 배송 정보를 입력해 주세요.",
    pickupIntro: "현장에서 본인을 확인할 이름과 연락처를 입력해 주세요.",
    name: "이름",
    nameHelp: "실제 수령할 때 사용할 성명을 입력해 주세요.",
    phone: "연락처",
    phoneHelp: "국가번호를 선택하고 연락 가능한 전화번호를 입력해 주세요.",
    postalCode: "우편번호",
    address1: "주소",
    address2: "상세 주소 (선택)",
    shippingCountry: "배송 국가",
    korea: "대한민국 (KR)",
    koreaOnly: "이 경품은 대한민국 내 주소로만 배송합니다.",
    deadline: "수령 정보 제출 마감",
    reviewTitle: "제출 정보 확인",
    reviewName: "성명",
    reviewPhone: "전화번호 뒤 4자리",
    privacy: "입력한 정보는 혜택 배송 또는 현장 수령에만 사용하며, 수령 완료 또는 미수령 종결 후 30일이 지나면 삭제합니다.",
    privacyLink: "개인정보처리방침 보기",
    consent: "[필수] 혜택 수령을 위한 개인정보 수집·이용에 동의합니다. 동의하지 않으면 실물 혜택을 받을 수 없습니다.",
    submit: "수령 정보 전달하기",
    submitting: "전달하는 중…",
    reconciling: "제출 상태를 확인하는 중이에요.",
    confirmTitle: "제출 상태 확인이 필요해요.",
    confirmBody: "중복 제출을 막기 위해 먼저 현재 상태를 확인해 주세요.",
    checkStatus: "제출 상태 다시 확인",
    retrySubmit: "상태를 확인했어요. 다시 제출할 수 있습니다.",
    success: "수령 정보를 전달했어요.",
    successBody: "MY에서 혜택의 진행 상태를 확인할 수 있어요.",
    currentStatus: "현재 수령 상태",
    noInput: "이 혜택은 수령 정보를 입력하지 않아도 돼요.",
    missing: "수령 정보를 확인할 수 없어요.",
    missingBody: "MY에서 혜택 상태를 다시 확인해 주세요.",
    unavailable: "수령 정보를 불러오지 못했어요.",
    session: "로그인이 필요해요.",
    sessionBody: "로그인한 뒤 내 혜택의 수령 정보를 입력할 수 있어요.",
    login: "로그인하고 계속하기",
    retry: "다시 시도",
    backMy: "MY에서 진행 상태 보기",
    benefit: "혜택 자세히 보기",
    loading: "수령 정보를 불러오는 중이에요.",
    required: "필수 입력",
    requiredError: "필수 항목을 입력해 주세요.",
    nameTooLong: "이름은 120자 이하로 입력해 주세요.",
    phoneLength: "연락처는 7자 이상 40자 이하로 입력해 주세요.",
    phoneInvalid: "선택한 국가에 맞는 전화번호를 입력해 주세요.",
    postalTooLong: "대한민국 우편번호 5자리를 입력해 주세요.",
    addressTooLong: "주소는 300자 이하로 입력해 주세요.",
    consentError: "개인정보 수집·이용에 동의해 주세요.",
    invalid: "입력 내용을 확인하고 다시 시도해 주세요.",
    deadlinePassed: "수령 정보 제출 기한이 지났어요.",
    deadlinePassedBody: "당첨 이력은 유지돼요. 제출과 관련해 도움이 필요하면 ByUs에 문의해 주세요.",
    unclaimed: "수령이 종료됐어요.",
    unclaimedBody: "당첨 이력은 유지돼요. 수령과 관련한 문의는 ByUs에 알려 주세요.",
    locked: "수령 정보가 접수됐어요.",
    lockedBody: "현재는 정보를 수정할 수 없어요. 변경이 필요하면 ByUs에 문의해 주세요.",
    contact: "ByUs에 문의하기",
  },
  en: {
    title: "Enter recipient details",
    editTitle: "Review recipient details",
    shippingIntro: "Enter the shipping details for your reward.",
    pickupIntro: "Enter the name and phone number used to verify you at pickup.",
    name: "Name",
    nameHelp: "Enter the full name you will use to receive the reward.",
    phone: "Phone number",
    phoneHelp: "Select a country calling code and enter a phone number where you can be reached.",
    postalCode: "Postal code",
    address1: "Address",
    address2: "Address line 2 (optional)",
    shippingCountry: "Shipping country",
    korea: "South Korea (KR)",
    koreaOnly: "This reward can only be shipped to an address in South Korea.",
    deadline: "Recipient details due",
    reviewTitle: "Review before submitting",
    reviewName: "Name",
    reviewPhone: "Last 4 digits of phone number",
    privacy: "We use this information only to deliver your reward or verify pickup, and delete it 30 days after fulfillment is completed or the claim is closed as unclaimed.",
    privacyLink: "View Privacy Policy",
    consent: "[Required] I agree to the collection and use of my personal information to receive this reward. Without consent, the physical reward cannot be fulfilled.",
    submit: "Submit recipient details",
    submitting: "Submitting…",
    reconciling: "Checking your submission status.",
    confirmTitle: "Your submission status needs confirmation.",
    confirmBody: "Check the current status before trying again to prevent a duplicate submission.",
    checkStatus: "Check submission status",
    retrySubmit: "Status confirmed. You can submit again.",
    success: "Your recipient details were submitted.",
    successBody: "You can follow the reward status in MY.",
    currentStatus: "Current fulfillment status",
    noInput: "This reward does not need recipient details.",
    missing: "We couldn’t find recipient details for this reward.",
    missingBody: "Check the reward status again in MY.",
    unavailable: "We couldn’t load the recipient details.",
    session: "Sign in required",
    sessionBody: "Sign in to enter recipient details for your reward.",
    login: "Sign in to continue",
    retry: "Try again",
    backMy: "View status in MY",
    benefit: "View reward details",
    loading: "Loading recipient details.",
    required: "Required",
    requiredError: "Complete this required field.",
    nameTooLong: "Enter a name of 120 characters or fewer.",
    phoneLength: "Enter a phone number between 7 and 40 characters.",
    phoneInvalid: "Enter a valid phone number for the selected country.",
    postalTooLong: "Enter a 5-digit South Korean postal code.",
    addressTooLong: "Enter an address of 300 characters or fewer.",
    consentError: "Agree to the collection and use of your personal information.",
    invalid: "Review your details and try again.",
    deadlinePassed: "The recipient details deadline has passed.",
    deadlinePassedBody: "Your winning history remains available. Contact ByUs if you need help with submission.",
    unclaimed: "Prize collection has closed.",
    unclaimedBody: "Your winning history remains available. Contact ByUs with collection questions.",
    locked: "Your recipient details were received.",
    lockedBody: "These details can no longer be edited. Contact ByUs if you need a change.",
    contact: "Contact ByUs",
  },
} as const;

export function recipientPath(winnerId: string, locale: AppLocale): string {
  return withLocalePath(`/my/rewards/${winnerId}/recipient`, locale);
}

export function selectOwnedRecipientReward(rewards: MyReward[], winnerId: string): MyReward | null {
  return rewards.find((reward) => reward.winnerId === winnerId) ?? null;
}

export const fulfillmentStatusLabel: Record<MyReward["status"], Record<AppLocale, string>> = {
  information_required: { ko: "정보 입력 필요", en: "Information required" },
  ready: { ko: "정보 접수 완료", en: "Information submitted" },
  shipping_preparing: { ko: "배송 준비 중", en: "Preparing shipment" },
  shipping_in_transit: { ko: "배송 중", en: "In transit" },
  shipping_completed: { ko: "배송 완료", en: "Delivered" },
  pickup_available: { ko: "수령 가능", en: "Ready for pickup" },
  pickup_completed: { ko: "수령 완료", en: "Picked up" },
  digital_delivered: { ko: "지급 완료", en: "Delivered" },
  not_selected: { ko: "미선정", en: "Not selected" },
};

export function formatRecipientDeadline(value: string, locale: AppLocale): string {
  const parts = new Intl.DateTimeFormat(locale === "ko" ? "ko-KR" : "en-CA", {
    timeZone: "Asia/Seoul",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hourCycle: "h23",
  }).formatToParts(new Date(value));
  const values = Object.fromEntries(parts.map((part) => [part.type, part.value]));
  return `${values.year}.${values.month}.${values.day} ${values.hour}:${values.minute} (KST)`;
}
