import { createClient } from "@supabase/supabase-js";
import { AuthError } from "@/features/auth/domain/auth-errors";
import { createPrivyNodeAccessVerifier } from "@/server/auth/privy-node-verifier";
import { loadServerEnv } from "@/server/config/env";
import { authorizeFanRequest } from "@/server/fan-auth/fan-auth-gate";
import { createSupabaseFanAuthRepository } from "@/server/fan-auth/supabase-fan-auth-repository";
import { SupabaseNotificationChannelRepository } from "@/server/notification/notification-channel-repository";
import { SupabaseKakaoPhoneEnrollmentRepository } from "@/server/notification/kakao-phone-enrollment";

export const dynamic="force-dynamic"; const responseHeaders={"cache-control":"private, no-store",vary:"Authorization"};
async function dependencies(request:Request){const e=loadServerEnv();const db=createClient(e.SUPABASE_URL,e.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const verifier=createPrivyNodeAccessVerifier({appId:e.PRIVY_APP_ID,appSecret:e.PRIVY_APP_SECRET,appEnvironment:e.PRIVY_APP_ENVIRONMENT,testAccountLoginEnabled:e.PRIVY_TEST_ACCOUNT_LOGIN_ENABLED, appleLoginEnabled: e.PRIVY_APPLE_LOGIN_ENABLED});const owner=await authorizeFanRequest({authorization:request.headers.get("authorization")??"",verifier,repository:createSupabaseFanAuthRepository({url:e.SUPABASE_URL,serviceRoleKey:e.SUPABASE_SERVICE_ROLE_KEY},db)});return {owner,repository:new SupabaseNotificationChannelRepository(db),enrollmentRepository:new SupabaseKakaoPhoneEnrollmentRepository(db),enrollmentEnabled:e.KAKAO_ALIMTALK_ENROLLMENT_ENABLED};}
export async function GET(request:Request){try{const {owner,repository,enrollmentRepository,enrollmentEnabled}=await dependencies(request);const [connections,pending]=await Promise.all([repository.listOwned(owner.appUserId),enrollmentEnabled?enrollmentRepository.getPending(owner.appUserId):Promise.resolve(null)]);return Response.json({connections,kakaoEnrollment:{enabled:enrollmentEnabled,pending}},{headers:responseHeaders});}catch(error){const status=error instanceof AuthError?error.status:503;return Response.json({error:{code:status===401?"UNAUTHENTICATED":"NOTIFICATION_CHANNELS_UNAVAILABLE"}},{status,headers:responseHeaders});}}
export async function PATCH(request:Request){try{const body=await request.json() as {channelId?:unknown;consented?:unknown;consentVersion?:unknown};if(typeof body.channelId!=="string"||typeof body.consented!=="boolean"||typeof body.consentVersion!=="string")return Response.json({error:{code:"INVALID_REQUEST"}},{status:400,headers:responseHeaders});const {owner,repository}=await dependencies(request);return Response.json({channel:await repository.setConsent({appUserId:owner.appUserId,channelId:body.channelId,consented:body.consented,consentVersion:body.consentVersion})},{headers:responseHeaders});}catch(error){const status=error instanceof AuthError?error.status:503;return Response.json({error:{code:status===401?"UNAUTHENTICATED":"NOTIFICATION_CHANNEL_UPDATE_FAILED"}},{status,headers:responseHeaders});}}
