import "server-only";
import { z } from "zod";
import { publicContentCacheHeaders } from "../cache/public-content-cache";
import type { CertificationDependencies } from "./certification-dependencies";
import { MAX_CERTIFICATION_FILE_BYTES, MAX_CERTIFICATION_MULTIPART_BYTES, normalizeCertificationImage, CertificationImageError } from "./certification-image";
import { boundedJson, boundedMultipart, correlation, json, locale, mapError, privateHeaders } from "./certification-http";

const uuid=z.uuid();
const submitSchema=z.object({missionId:uuid,idem:uuid,uploadIds:z.array(uuid).min(1).max(3),note:z.string().trim().min(1).max(1000).optional(),previousSubmissionId:uuid.optional()}).strict().refine(value=>new Set(value.uploadIds).size===value.uploadIds.length);
const saveSchema=z.object({command:z.literal("save"),id:uuid.optional(),celebrityId:uuid,immutableKey:z.string().regex(/^[a-z0-9][a-z0-9_-]{2,79}$/),expectedRevision:z.number().int().positive().optional(),membershipPlatform:z.enum(["instagram","tiktok","youtube"]).optional(),category:z.string().trim().min(1).max(60),titleKo:z.string().trim().min(1).max(160),titleEn:z.string().trim().min(1).max(160),descriptionKo:z.string().trim().min(1).max(1200),descriptionEn:z.string().trim().min(1).max(1200),instructionsKo:z.string().trim().min(1).max(3000),instructionsEn:z.string().trim().min(1).max(3000),opensAt:z.iso.datetime({offset:true}),closesAt:z.iso.datetime({offset:true}),scorePoints:z.number().int().min(0).max(100),ticketAmount:z.number().int().min(0).max(1_000_000)}).strict().superRefine((v,c)=>{if(v.membershipPlatform&&(v.scorePoints<1||v.ticketAmount!==0))c.addIssue({code:"custom",message:"membership rewards require positive score and no tickets"});if(Date.parse(v.opensAt)>=Date.parse(v.closesAt))c.addIssue({code:"custom",message:"invalid mission window"});if((v.id===undefined)!==(v.expectedRevision===undefined))c.addIssue({code:"custom",message:"id and expectedRevision must be provided together"});});
const statusSchema=z.object({command:z.enum(["activate","close"]),id:uuid,expectedRevision:z.number().int().positive()}).strict();
const reviewSchema=z.object({idem:uuid,expectedRevision:z.number().int().positive(),decision:z.enum(["approve","reject"]),rejectionReason:z.string().trim().min(3).max(1000).optional()}).strict().superRefine((v,c)=>{if((v.decision==="reject")!==Boolean(v.rejectionReason))c.addIssue({code:"custom",message:"reason must match decision"});});

async function fan(request:Request,deps:CertificationDependencies){return deps.authorizeFan(request.headers.get("authorization"));}
async function admin(request:Request,deps:CertificationDependencies){return deps.authorizeAdmin(request.headers.get("authorization")??"",correlation(request));}
function isUploadedFile(value:FormDataEntryValue):value is File{return typeof value==="object"&&value!==null&&typeof (value as File).arrayBuffer==="function"&&typeof (value as File).size==="number"&&typeof (value as File).type==="string";}

export const certificationRoutes={
  publicList:(deps:CertificationDependencies)=>async(request:Request,input:{slug:string})=>{const lang=locale(request);if(!lang)return json({error:{code:"INVALID_LOCALE"}},400);try{return json({certifications:await deps.repository.listPublic(input.slug,lang)},200,publicContentCacheHeaders());}catch(e){return mapError(e);}},
  publicDetail:(deps:CertificationDependencies)=>async(request:Request,input:{id:string})=>{const lang=locale(request);if(!lang||!uuid.safeParse(input.id).success)return json({error:{code:"INVALID_REQUEST"}},400);try{const certification=await deps.repository.getPublic(input.id,lang);return certification?json({certification},200,publicContentCacheHeaders()):json({error:{code:"NOT_FOUND"}},404);}catch(e){return mapError(e);}},
  history:(deps:CertificationDependencies)=>async(request:Request,input:{slug:string})=>{const lang=locale(request);if(!lang)return json({error:{code:"INVALID_LOCALE"}},400);try{const owner=await fan(request,deps);return json({certifications:await deps.repository.history(owner.appUserId,input.slug,lang)});}catch(e){return mapError(e);}},
  submission:(deps:CertificationDependencies)=>async(request:Request,input:{id:string})=>{const lang=locale(request);if(!lang||!uuid.safeParse(input.id).success)return json({error:{code:"INVALID_REQUEST"}},400);try{const owner=await fan(request,deps);const submission=await deps.repository.getSubmission(owner.appUserId,input.id,lang);return submission?json({submission}):json({error:{code:"NOT_FOUND"}},404);}catch(e){return mapError(e);}},
  submit:(deps:CertificationDependencies)=>async(request:Request)=>{try{const owner=await fan(request,deps);const body=submitSchema.parse(await boundedJson(request));return json({submission:await deps.repository.submit({appUserId:owner.appUserId,idempotencyKey:body.idem,...body})},201);}catch(e){if(e instanceof z.ZodError||e instanceof SyntaxError)return json({error:{code:"INVALID_REQUEST"}},400);return mapError(e);}},
  upload:(deps:CertificationDependencies)=>async(request:Request,input:{id:string})=>{if(!uuid.safeParse(input.id).success)return json({error:{code:"INVALID_REQUEST"}},400);try{const owner=await fan(request,deps);const form=await boundedMultipart(request,MAX_CERTIFICATION_MULTIPART_BYTES);const entries=[...form.entries()];const file=entries.length===1&&entries[0][0]==="file"&&isUploadedFile(entries[0][1])?entries[0][1]:null;if(!file)return json({error:{code:"INVALID_IMAGE"}},400);if(file.size>MAX_CERTIFICATION_FILE_BYTES)return json({error:{code:"BODY_TOO_LARGE"}},413);const normalized=await normalizeCertificationImage(new Uint8Array(await file.arrayBuffer()));return json(await deps.repository.upload(owner.appUserId,input.id,normalized),201);}catch(e){if(e instanceof CertificationImageError)return json({error:{code:e.code}},e.code==="BODY_TOO_LARGE"?413:400);return mapError(e);}},
  ownerProof:(deps:CertificationDependencies)=>async(request:Request,input:{id:string;uploadId:string})=>{try{const owner=await fan(request,deps);const file=await deps.repository.proofForOwner(owner.appUserId,input.id,input.uploadId);return file?new Response(file.bytes,{headers:{...privateHeaders,"content-type":file.contentType,"content-disposition":"inline"}}):json({error:{code:"NOT_FOUND"}},404);}catch(e){return mapError(e);}},
  adminMissions:(deps:CertificationDependencies)=>async(request:Request)=>{try{const actor=await admin(request,deps);if(request.method==="GET")return json({missions:await deps.repository.listAdmin(actor)});const body=await boundedJson(request);const parsed=z.union([saveSchema,statusSchema]).parse(body);const result=parsed.command==="save"?await deps.repository.saveAdmin(actor,correlation(request),parsed):await deps.repository.statusAdmin(actor,correlation(request),{id:parsed.id,expectedRevision:parsed.expectedRevision,status:parsed.command==="activate"?"active":"closed"});return json({mission:result});}catch(e){if(e instanceof z.ZodError||e instanceof SyntaxError)return json({error:{code:"INVALID_REQUEST"}},400);return mapError(e);}},
  adminQueue:(deps:CertificationDependencies)=>async(request:Request)=>{const status=new URL(request.url).searchParams.get("status")??"pending";if(!["pending","approved","rejected"].includes(status))return json({error:{code:"INVALID_STATUS"}},400);try{const actor=await admin(request,deps);return json({submissions:await deps.repository.queueAdmin(actor,status as "pending"|"approved"|"rejected")});}catch(e){return mapError(e);}},
  adminReview:(deps:CertificationDependencies)=>async(request:Request,input:{id:string})=>{try{const actor=await admin(request,deps);const body=reviewSchema.parse(await boundedJson(request));return json({submission:await deps.repository.reviewAdmin(actor,correlation(request),input.id,body)});}catch(e){if(e instanceof z.ZodError||e instanceof SyntaxError)return json({error:{code:"INVALID_REQUEST"}},400);return mapError(e);}},
  adminProof:(deps:CertificationDependencies)=>async(request:Request,input:{id:string;uploadId:string})=>{try{const actor=await admin(request,deps);const file=await deps.repository.proofForAdmin(actor,input.id,input.uploadId);return file?new Response(file.bytes,{headers:{...privateHeaders,"content-type":file.contentType,"content-disposition":"inline"}}):json({error:{code:"NOT_FOUND"}},404);}catch(e){return mapError(e);}},
};
