create function public.read_admin_live_analytics(p_actor_app_user_id uuid,p_actor_admin_allowlist_id uuid,p_live_event_id uuid,p_from timestamptz,p_to timestamptz,p_as_of timestamptz)
returns jsonb language plpgsql volatile security definer set search_path='' as $$
declare e public.live_events%rowtype; title text; visits integer;reservations integer;attendances integer;completions integer;claims integer;mission_participants integer;result jsonb;
begin
  perform public.assert_blockchain_job_admin_actor(p_actor_app_user_id,p_actor_admin_allowlist_id,false);
  perform public.validate_admin_analytics_window(p_from,p_to,p_as_of);
  select * into e from public.live_events where id=p_live_event_id;if not found then raise exception 'LIVE_NOT_FOUND' using errcode='P0002';end if;
  select coalesce(l.title,e.slug) into title from public.live_events x left join public.live_event_localizations l on l.live_event_id=x.id and l.locale='ko' where x.id=e.id;
  select count(distinct coalesce(app_user_id::text,anonymous_session_hash))::integer into visits from public.fan_product_events where event_name='live_page_view' and live_event_id=e.id and occurred_at>=p_from and occurred_at<p_to;
  select count(distinct app_user_id)::integer into reservations from public.live_reservations where live_event_id=e.id and reserved_at>=p_from and reserved_at<p_to;
  select count(distinct app_user_id)::integer into attendances from public.live_attendances where live_event_id=e.id and attended_at>=p_from and attended_at<p_to;
  select count(distinct app_user_id)::integer into completions from public.live_journey_completions where live_event_id=e.id and completed_at>=p_from and completed_at<p_to;
  select count(distinct app_user_id)::integer into claims from public.live_collectible_claims where live_event_id=e.id and claimed_at>=p_from and claimed_at<p_to;
  select count(distinct app_user_id)::integer into mission_participants from public.live_survey_responses where live_event_id=e.id and status='submitted' and submitted_at>=p_from and submitted_at<p_to;
  with job_facts as(
    select j.id,j.entity_type,j.status,j.created_at,p.app_user_id from public.blockchain_jobs j join public.fan_passports p on j.entity_type='passport' and p.id=j.entity_id where p.celebrity_id=e.celebrity_id
    union all select j.id,j.entity_type,j.status,j.created_at,r.app_user_id from public.blockchain_jobs j join public.fan_reactions r on j.entity_type='reaction' and r.id=j.entity_id where r.celebrity_id=e.celebrity_id
    union all select j.id,j.entity_type,j.status,j.created_at,s.app_user_id from public.blockchain_jobs j join public.stamps s on j.entity_type='stamp' and s.id=j.entity_id join public.fan_activities a on a.id=s.activity_id left join public.live_reservations r on a.source_type='live_reservation' and r.id=a.source_id left join public.live_attendances d on a.source_type='live_attendance' and d.id=a.source_id left join public.live_survey_responses m on a.source_type='live_survey_response' and m.id=a.source_id where coalesce(r.live_event_id,d.live_event_id,m.live_event_id)=e.id
    union all select j.id,j.entity_type,j.status,j.created_at,c.app_user_id from public.blockchain_jobs j join public.live_collectible_claims c on j.entity_type='collectible' and c.id=j.entity_id where c.live_event_id=e.id
  ),eligible as(
    select distinct p.app_user_id from public.live_journey_participations p join public.live_journey_requirement_revisions r on r.id=p.requirement_revision_id where p.live_event_id=e.id and p.bound_at<p_to
      and(not r.require_passport or exists(select 1 from public.fan_passports x where x.app_user_id=p.app_user_id and x.celebrity_id=e.celebrity_id and x.issued_at<p_to))
      and(not r.require_reservation or exists(select 1 from public.live_reservations x where x.app_user_id=p.app_user_id and x.live_event_id=e.id and x.reserved_at<p_to))
      and(not r.require_attendance or exists(select 1 from public.live_attendances x where x.app_user_id=p.app_user_id and x.live_event_id=e.id and x.attended_at<p_to))
  ),missions as(
    select m.id,coalesce(ml.title,'Mission') title,m.mission_type,count(distinct r.app_user_id)::integer participants,count(*)filter(where r.correctness=true)::integer correct,count(*)filter(where r.correctness=false)::integer incorrect
    from public.live_surveys m left join public.live_survey_localizations ml on ml.survey_id=m.id and ml.locale='ko' left join public.live_survey_responses r on r.survey_id=m.id and r.status='submitted' and r.submitted_at>=p_from and r.submitted_at<p_to where m.live_event_id=e.id and m.publication_status='published' group by m.id,ml.title,m.mission_type
  )
  select jsonb_build_object(
    'live',jsonb_build_object('id',e.id,'title',title,'startsAt',e.starts_at,'endsAt',e.ends_at),'window',jsonb_build_object('from',p_from,'to',p_to,'semantics','[from,to)','asOf',p_as_of,'timeZone','Asia/Seoul'),
    'funnel',jsonb_build_object('visits',jsonb_build_object('state','available','value',visits,'reason',null,'source','fan_product_events(live_page_view)'),'reservations',jsonb_build_object('state','available','value',reservations,'reason',null,'source','live_reservations'),'reservationRate',case when visits=0 then jsonb_build_object('state','not_applicable','value',null,'reason','NO_VISITS_IN_WINDOW','source','live_reservations/fan_product_events(live_page_view)')else jsonb_build_object('state','available','value',jsonb_build_object('numerator',reservations,'denominator',visits,'rate',least(1,reservations::numeric/visits)),'reason',null,'source','live_reservations/fan_product_events(live_page_view)')end,'attendances',jsonb_build_object('state','available','value',attendances,'reason',null,'source','live_attendances'),'attendanceRate',case when reservations=0 then jsonb_build_object('state','not_applicable','value',null,'reason','NO_RESERVATIONS_IN_WINDOW','source','live_attendances/live_reservations')else jsonb_build_object('state','available','value',jsonb_build_object('numerator',attendances,'denominator',reservations,'rate',least(1,attendances::numeric/reservations)),'reason',null,'source','live_attendances/live_reservations')end),
    'relationships',jsonb_build_object('newFans',jsonb_build_object('state','available','value',(select count(distinct p.app_user_id)::integer from public.fan_passports p join public.quiz_pass_attributions a on a.quiz_pass_id=p.quiz_pass_id where a.source_type='live' and a.source_id=e.id and p.issued_at>=p_from and p.issued_at<p_to),'reason',null,'source','quiz_pass_attributions/fan_passports'),'newPassports',jsonb_build_object('state','available','value',(select count(*)::integer from public.fan_passports p join public.quiz_pass_attributions a on a.quiz_pass_id=p.quiz_pass_id where a.source_type='live' and a.source_id=e.id and p.issued_at>=p_from and p.issued_at<p_to),'reason',null,'source','quiz_pass_attributions/fan_passports'),'firstReactions',jsonb_build_object('state','available','value',(select count(*)::integer from public.fan_reactions where celebrity_id=e.celebrity_id and completed_at>=p_from and completed_at<p_to),'reason',null,'source','fan_reactions')),
    'missions',case when mission_participants between 1 and 4 then jsonb_build_object('state','suppressed','value',null,'reason','SMALL_COHORT_LT_5','source','live_survey_responses')else jsonb_build_object('state','available','value',coalesce((select jsonb_agg(jsonb_build_object('missionId',m.id,'title',m.title,'type',m.mission_type,'participants',m.participants,'participationRate',case when attendances=0 then null else least(1,m.participants::numeric/attendances)end,'correct',case when m.mission_type='quiz' then m.correct else null end,'incorrect',case when m.mission_type='quiz' then m.incorrect else null end,'correctRate',case when m.mission_type='quiz'and m.participants>0 then m.correct::numeric/m.participants else null end,'options',coalesce((select jsonb_agg(jsonb_build_object('optionId',o.id,'label',coalesce(ol.label,'Option'),'responses',(select count(*)::integer from public.live_survey_answers a join public.live_survey_responses r on r.id=a.response_id where r.survey_id=m.id and r.status='submitted' and r.submitted_at>=p_from and r.submitted_at<p_to and o.id=any(a.selected_option_ids)))order by o.position)from public.live_survey_questions q join public.live_survey_options o on o.question_id=q.id left join public.live_survey_option_localizations ol on ol.option_id=o.id and ol.locale='ko' where q.survey_id=m.id),'[]'::jsonb)))from missions m),'[]'::jsonb),'reason',null,'source','live_surveys/live_survey_responses/live_survey_answers')end,
    'benefits',jsonb_build_object('ticketsEarned',jsonb_build_object('state','available','value',(select coalesce(sum(l.amount),0)::integer from public.fan_ticket_ledger l where l.entry_kind='credit'and l.created_at>=p_from and l.created_at<p_to and(l.source_id in(select id from public.live_reservations where live_event_id=e.id)or l.source_id in(select id from public.live_attendances where live_event_id=e.id)or l.source_id in(select id from public.live_survey_responses where live_event_id=e.id)or l.source_id in(select id from public.live_journey_completions where live_event_id=e.id))),'reason',null,'source','fan_ticket_ledger'),'ticketsUsed',jsonb_build_object('state','available','value',(select coalesce(sum(b.ticket_amount),0)::integer from public.benefit_ticket_entries b join public.live_benefit_campaigns c on c.id=b.campaign_id where c.live_event_id=e.id and b.entered_at>=p_from and b.entered_at<p_to),'reason',null,'source','benefit_ticket_entries/fan_ticket_ledger'),'applicants',jsonb_build_object('state','available','value',(select count(distinct b.app_user_id)::integer from public.benefit_ticket_entries b join public.live_benefit_campaigns c on c.id=b.campaign_id where c.live_event_id=e.id and b.entered_at>=p_from and b.entered_at<p_to),'reason',null,'source','benefit_ticket_entries'),'winners',jsonb_build_object('state','available','value',(select count(distinct w.app_user_id)::integer from public.benefit_draw_winners w join public.live_benefit_campaigns c on c.id=w.campaign_id where c.live_event_id=e.id and w.selected_at>=p_from and w.selected_at<p_to),'reason',null,'source','benefit_draw_winners')),
    'journey',jsonb_build_object('eligible',jsonb_build_object('state','available','value',(select count(*)::integer from eligible),'reason',null,'source','live_journey_participations plus canonical requirements'),'complete',jsonb_build_object('state','available','value',completions,'reason',null,'source','live_journey_completions'),'claims',jsonb_build_object('state','available','value',claims,'reason',null,'source','live_collectible_claims'),'claimRate',case when completions=0 then jsonb_build_object('state','not_applicable','value',null,'reason','NO_JOURNEY_COMPLETIONS_IN_WINDOW','source','live_collectible_claims/live_journey_completions')else jsonb_build_object('state','available','value',jsonb_build_object('numerator',claims,'denominator',completions,'rate',least(1,claims::numeric/completions)),'reason',null,'source','live_collectible_claims/live_journey_completions')end),
    'chain',jsonb_build_object('total',jsonb_build_object('state','available','value',(select count(*)::integer from job_facts where created_at>=p_from and created_at<p_to),'reason',null,'source','blockchain_jobs'),'uniqueFans',jsonb_build_object('state','available','value',(select count(distinct app_user_id)::integer from job_facts where created_at>=p_from and created_at<p_to),'reason',null,'source','blockchain_jobs linked operational owners'),'successful',jsonb_build_object('state','available','value',(select count(*)::integer from job_facts where status='COMPLETED'and created_at>=p_from and created_at<p_to),'reason',null,'source','blockchain_jobs(status=COMPLETED)'),'pending',jsonb_build_object('state','available','value',(select count(*)::integer from job_facts where status in('PENDING','PROCESSING','RETRYING')and created_at>=p_from and created_at<p_to),'reason',null,'source','blockchain_jobs(status=PENDING|PROCESSING|RETRYING)'),'failed',jsonb_build_object('state','available','value',(select count(*)::integer from job_facts where status='FAILED'and created_at>=p_from and created_at<p_to),'reason',null,'source','blockchain_jobs(status=FAILED)'),'breakdown',jsonb_build_object('state','available','value',jsonb_build_object('passport',(select count(*)::integer from job_facts where entity_type='passport'and created_at>=p_from and created_at<p_to),'reaction',(select count(*)::integer from job_facts where entity_type='reaction'and created_at>=p_from and created_at<p_to),'stamp',(select count(*)::integer from job_facts where entity_type='stamp'and created_at>=p_from and created_at<p_to),'collectible',(select count(*)::integer from job_facts where entity_type='collectible'and created_at>=p_from and created_at<p_to)),'reason',null,'source','blockchain_jobs.entity_type'))
  )into result;
  return result;
end$$;
revoke all on function public.read_admin_live_analytics(uuid,uuid,uuid,timestamptz,timestamptz,timestamptz)from public,anon,authenticated;
grant execute on function public.read_admin_live_analytics(uuid,uuid,uuid,timestamptz,timestamptz,timestamptz)to service_role;
