-- Generated by Supabase CLI as 20260911184322, then renumbered so this forward
-- migration follows the repository's unpublished 20260912030000 migration.
-- Fan identity is public once an active user has completed a like or received a Passport.
-- The former visibility preference remains stored for compatibility but no longer gates reads.
create or replace function public.read_celebrity_fan_community(
  p_slug text,p_locale public.content_locale default 'ko'
) returns jsonb language sql stable security definer set search_path='' as $$
  with creator as (
    select c.id
    from public.celebrities c
    join public.celebrity_localizations l on l.celebrity_id=c.id and l.locale=p_locale
    where c.slug=p_slug and c.status='published' and c.archived_at is null
  ), completed as materialized (
    select r.app_user_id,r.completed_at
    from public.fan_reactions r
    join creator c on c.id=r.celebrity_id
    join public.app_users u on u.id=r.app_user_id and u.status='active'
    where r.business_status='completed'
  ), eligible_events as materialized (
    select r.app_user_id,r.completed_at occurred_at from completed r
    union all
    select p.app_user_id,p.issued_at
    from public.fan_passports p
    join creator c on c.id=p.celebrity_id
    join public.app_users u on u.id=p.app_user_id and u.status='active'
    where p.business_status='issued'
  ), eligible as materialized (
    select app_user_id,max(occurred_at) occurred_at
    from eligible_events
    group by app_user_id
  ), selected as (
    select e.app_user_id,e.occurred_at,
      coalesce(nullif(btrim(p.nickname),''),case when p_locale='ko' then '팬' else 'Fan' end) nickname,
      '/images/avatars/'||coalesce(a.selected_character_id,'star-pink')||'.webp' avatar_url
    from eligible e
    left join public.user_profiles p on p.app_user_id=e.app_user_id
    left join public.app_user_avatars a on a.app_user_id=e.app_user_id
    order by e.occurred_at desc,e.app_user_id
    limit 24
  )
  select jsonb_build_object(
    'likeCount',(select count(distinct app_user_id) from completed),
    'fanCount',(select count(*) from eligible),
    'publicFanCount',(select count(*) from eligible),
    'fans',coalesce((select jsonb_agg(jsonb_build_object(
      'nickname',nickname,'avatarUrl',avatar_url
    ) order by occurred_at desc,app_user_id) from selected),'[]'::jsonb)
  ) from creator;
$$;

create or replace function public.read_celebrity_fanpage(
  p_slug text,p_locale public.content_locale
) returns jsonb language sql stable security definer set search_path='' as $$
  with creator as (
    select c.id
    from public.celebrities c
    join public.celebrity_localizations l on l.celebrity_id=c.id and l.locale=p_locale
    where c.slug=p_slug and c.status='published' and c.archived_at is null
  ), members as (
    select p.app_user_id,p.issued_at from public.fan_passports p
    join creator c on c.id=p.celebrity_id join public.app_users u on u.id=p.app_user_id
    where p.business_status='issued' and u.status='active'
  ), events as (
    select m.app_user_id,'joined'::text kind,null::text tier,m.issued_at occurred_at from members m
    union all select e.app_user_id,'level_up',e.current_level,e.occurred_at
    from public.fan_level_events e join creator c on c.id=e.celebrity_id join members m on m.app_user_id=e.app_user_id
    union all select s.app_user_id,'first_certification',null,min(s.reviewed_at)
    from public.certification_submissions s join creator c on c.id=s.celebrity_id join members m on m.app_user_id=s.app_user_id
    where s.status='approved' group by s.app_user_id
  ), recent as (
    select e.*,coalesce(nullif(btrim(p.nickname),''),case when p_locale='ko' then '팬' else 'Fan' end) nickname,
      '/images/avatars/'||coalesce(a.selected_character_id,'star-pink')||'.webp' avatar_url
    from events e
    left join public.user_profiles p on p.app_user_id=e.app_user_id
    left join public.app_user_avatars a on a.app_user_id=e.app_user_id
    order by e.occurred_at desc,e.app_user_id,e.kind limit 6
  )
  select jsonb_build_object(
    'membershipCount',(select count(*) from members),
    'leaderboardAvailable',(select count(*)>500 from members),
    'activity',coalesce((select jsonb_agg(jsonb_build_object(
      'kind',kind,'tier',tier,'nickname',nickname,'avatarUrl',avatar_url,'occurredAt',occurred_at
    ) order by occurred_at desc,app_user_id,kind) from recent),'[]'::jsonb)
  ) from creator;
$$;

create or replace function public.read_celebrity_fanpage(p_slug text)
returns jsonb language sql stable security definer set search_path='' as $$
  select public.read_celebrity_fanpage(p_slug,'ko'::public.content_locale);
$$;

revoke all on function public.read_owned_fan_activity_visibility(uuid),
  public.set_owned_fan_activity_visibility(uuid,boolean)
  from public,anon,authenticated,service_role;

revoke all on function public.read_celebrity_fan_community(text,public.content_locale),
  public.read_celebrity_fanpage(text,public.content_locale),
  public.read_celebrity_fanpage(text)
  from public,anon,authenticated,service_role;
grant execute on function public.read_celebrity_fan_community(text,public.content_locale),
  public.read_celebrity_fanpage(text,public.content_locale),
  public.read_celebrity_fanpage(text)
  to service_role;
