export const elinaFanGuideContent = {
  ko: {
    heroTitle: "엘리나와 함께하는\n뱅크시 LIVE",
    heroDescription: "팬 인증하고 LIVE를 예약하면 응모권 2장.\n지금 원하는 선물에 응모해 보세요.",
    heroSchedule: "9월 18일(금) 오후 8:30 · Instagram LIVE · KST",
    prizeSummary: "뱅크시 관람권 60명 · 비피오 랜덤 케이스 10명 · 뱅크시 한정판 스태츄 3명 추첨",
    howToJoin: "팬 인증하고 시작하기",
    viewPrizes: "경품 3종 보기",
    heroNote: "팬 인증·예약 보상은 각각 처음 완료할 때 1회 지급돼요.\n응모권을 받은 뒤 원하는 경품에 직접 응모해 주세요.",
    stages: ["팬 인증 +1장", "LIVE 예약 +1장", "지금 선물 응모", "방송 당일 +2장"],
    steps: [
      {
        label: "01  /  방송 전",
        title: "팬 인증하고\n첫 응모권 1장을 받아요.",
        body: "로그인 후 엘리나 퀴즈 3문항 중 2문항 이상을 맞히면 Fan Passport와 응모권 1장을 받아요. 인증이 끝나면 LIVE 예약 화면으로 이어져요.",
        actions: ["팬 인증하기"],
        note: "이미 인증했다면 LIVE 예약으로 이어서 진행하세요. 같은 인증으로 응모권이 다시 지급되지는 않아요.",
      },
      {
        label: "02  /  방송 전",
        title: "LIVE 예약하고\n응모권 1장을 더 받아요.",
        body: "9월 18일 오후 8시 30분, 엘리나의 Instagram LIVE를 예약하세요. 최초 예약을 완료하면 응모권 1장이 더 생겨요.",
        actions: ["엘리나 LIVE 예약하기"],
        note: "예약은 9월 18일 오후 8시 20분(KST)에 마감돼요. 엘리나 Passport가 필요해요.",
      },
      {
        label: "03  /  지금 응모",
        title: "모은 2장으로,\n원하는 선물에 응모해요.",
        body: "팬 인증과 LIVE 예약을 처음 완료했다면 응모권 2장으로 바로 응모할 수 있어요. 방송까지 기다릴 필요 없어요. 원하는 경품을 고르고 사용할 수량을 확인해 주세요.",
        actions: ["선물 고르고 응모하기"],
        note: "응모권은 경품 3종이 함께 사용해요. 한 경품에 쓰면 남은 수량이 줄어들어요. 응모 마감은 9월 28일 00:00(KST), 9월 27일에서 28일로 넘어가는 자정이에요.",
      },
      {
        label: "04  /  9월 18일 방송 당일",
        title: "방송을 보고 출석하면\n응모권 2장을 더 받아요.",
        body: "Instagram에서 LIVE를 시청하고, 방송에서 알려주는 코드를 ByUs의 LIVE 화면에 입력하세요. 출석을 완료하면 응모권 2장을 받아 원하는 선물에 추가로 응모할 수 있어요.",
        actions: ["출석할 LIVE 화면 보기", "선물 응모하러 가기"],
        note: "코드 입력은 9월 18일 오후 8시 30분~9시 30분(KST)에 가능해요. 방송을 보다가 이 ByUs 화면으로 돌아와 주세요. 예약과 출석은 별도이며, 엘리나 Passport가 필요해요.",
      },
    ],
    liveCard: {
      title: "엘리나와 함께하는 뱅크시 LIVE",
      flow: "9월 18일(금) 오후 8:30 · Instagram",
      code: "예약 마감 · KST",
      value: "9월 18일 오후 8:20",
    },
    missionCards: [
      ["Instagram에서 LIVE 시청", "9월 18일 오후 8:30 · KST"],
      ["ByUs로 돌아와 코드 입력", "출석 완료 시 응모권 +2장"],
    ],
    historyTitle: "예약과 응모 완료를 확인하세요.",
    historyBody: "MY에서 예약한 LIVE, 내 응모 내역과 발표 후 당첨 여부를 확인할 수 있어요.",
    historyAction: "내 기록 보기",
    faqTitle: "시작하기 전에, 궁금한 것들",
    faqs: [
      ["방송 전에도 선물에 응모할 수 있나요?", "네. 팬 인증으로 1장, LIVE 예약으로 1장을 받아 바로 응모할 수 있어요. 각 보상은 처음 완료할 때 한 번만 지급돼요."],
      ["예약하거나 출석하면 자동으로 응모되나요?", "아니요. 응모권을 받은 뒤 경품을 고르고 사용할 수량을 확인해 직접 응모해야 해요."],
      ["이미 팬 인증이나 예약을 했다면요?", "같은 활동의 응모권은 다시 지급되지 않아요. 보유 응모권으로 응모하고, 방송 당일 출석으로 2장을 추가로 받을 수 있어요."],
      ["좋아요를 누르면 응모권을 받나요?", "좋아요에는 응모권이 지급되지 않아요. 팬 인증, LIVE 예약, 방송 당일 출석으로 모아 주세요."],
      ["해외에서도 경품을 받을 수 있나요?", "전시 관람권은 더현대 서울 현장에서 수령하고 사용해요. 배송 경품은 대한민국 주소로만 받을 수 있어요. 응모 전 각 경품의 수령 조건을 확인해 주세요."],
      ["당첨되면 어떻게 확인하나요?", "결과 발표 후 MY의 응모 내역에서 확인하세요. 당첨자는 발표 후 7일 안에 수령정보를 입력해야 해요."],
    ],
    closingTitle: "팬 인증부터 LIVE 예약까지,\n지금 시작해 볼까요?",
    closingAction: "팬 인증하고 시작하기",
    footer: "ByUs. Your Bias.    ·    한국어 / EN",
    imageAlt: "바다를 배경으로 선 엘리나",
    prizeAlt: "전시 공간에 걸린 작품을 바라보는 관람객",
  },
  en: {
    heroTitle: "Banksy LIVE\nwith Elina",
    heroDescription: "Verify your fandom and reserve your spot to earn 2 raffle tickets. Enter for your favorite prize now.",
    heroSchedule: "September 18 · 8:30 PM KST · Instagram LIVE",
    prizeSummary: "60 exhibition ticket winners · 10 Beepio random case winners · 3 Banksy limited-edition statue winners",
    howToJoin: "Verify and get started",
    viewPrizes: "View all 3 prizes",
    heroNote: "Verification and reservation rewards are each granted once. Earning tickets does not enter you automatically.",
    stages: ["Verify +1 ticket", "Reserve +1 ticket", "Enter now", "LIVE check-in +2"],
    steps: [
      {
        label: "01  /  BEFORE THE LIVE",
        title: "Verify your fandom.\nEarn your first ticket.",
        body: "Sign in and answer at least 2 of Elina’s 3 quiz questions correctly to receive your Fan Passport and 1 raffle ticket. Then continue to the LIVE reservation page.",
        actions: ["Verify your fandom"],
        note: "Already verified? Continue to the LIVE reservation. Verification does not grant another ticket when repeated.",
      },
      {
        label: "02  /  BEFORE THE LIVE",
        title: "Reserve your spot.\nEarn 1 more ticket.",
        body: "Reserve a spot for Elina’s Instagram LIVE on September 18 at 8:30 PM KST. Your first completed reservation earns 1 raffle ticket.",
        actions: ["Reserve a spot"],
        note: "Reservations close September 18 at 8:20 PM KST. An Elina Passport is required.",
      },
      {
        label: "03  /  ENTER NOW",
        title: "Use your 2 tickets.\nChoose your prize.",
        body: "After completing fan verification and this LIVE reservation for the first time, you can enter with 2 tickets right away. No need to wait for the broadcast. Choose a prize and review how many tickets to use.",
        actions: ["Choose a prize and enter"],
        note: "Your Elina ticket balance is shared across all 3 prizes. Tickets used for one prize are deducted from that balance. Entries close at midnight KST at the end of September 27 (September 28, 00:00).",
      },
      {
        label: "04  /  SEPTEMBER 18",
        title: "Watch and check in.\nEarn 2 more tickets.",
        body: "Watch the LIVE on Instagram, then return to the ByUs LIVE page and enter the code shared during the broadcast. Complete check-in to earn 2 raffle tickets, then use them to enter for your favorite prize.",
        actions: ["Open the LIVE check-in page", "Enter for a prize"],
        note: "Code entry is open September 18, 8:30–9:30 PM KST. Return to the ByUs LIVE page after watching on Instagram. Check-in is separate from reservation and requires an Elina Passport.",
      },
    ],
    liveCard: {
      title: "Banksy LIVE with Elina",
      flow: "September 18 · 8:30 PM KST · Instagram",
      code: "Reservations close",
      value: "Sep 18 · 8:20 PM KST",
    },
    missionCards: [
      ["Watch on Instagram", "September 18 · 8:30 PM KST"],
      ["Return to ByUs and enter the code", "Complete check-in to earn +2 tickets"],
    ],
    historyTitle: "Check your reservation and entries.",
    historyBody: "Find your reserved LIVE and raffle entries in MY. Results appear there after the announcement.",
    historyAction: "View my history",
    faqTitle: "Before you get started",
    faqs: [
      ["Can I enter before the LIVE?", "Yes. Earn 1 ticket from fan verification and 1 from your LIVE reservation, then enter right away. Each reward is granted only once."],
      ["Does reserving or checking in enter me automatically?", "No. After earning tickets, choose a prize, review the quantity and confirm your entry."],
      ["What if I have already verified or reserved?", "Repeating the same activity does not grant more tickets. Use your current balance, then earn 2 more tickets by checking in during the LIVE."],
      ["Do likes earn raffle tickets?", "Likes do not earn raffle tickets. Earn them through fan verification, LIVE reservation and check-in."],
      ["Can I receive prizes overseas?", "Exhibition tickets must be collected and used at The Hyundai Seoul. Shipped prizes require an address in South Korea. Check each prize’s collection conditions before entering."],
      ["How do I check whether I won?", "After results are announced, check your entries in MY. Winners must submit recipient details within 7 days of the announcement."],
    ],
    closingTitle: "Start with fan verification,\nthen reserve your spot.",
    closingAction: "Verify and get started",
    footer: "ByUs. Your Bias.    ·    KO / English",
    imageAlt: "Elina standing by the sea",
    prizeAlt: "A visitor viewing artwork in an exhibition space",
  },
} as const;
