export const elinaFanGuideContent = {
  ko: {
    heroTitle: "좋아하는 마음이,\n함께한 순간으로.",
    heroDescription:
      "엘리나와 함께하는 ByUs 참여 가이드\n팬 인증부터 LIVE, 미션, 선물 응모까지.",
    howToJoin: "참여 방법 보기",
    viewPrizes: "선물 보기",
    heroNote: "처음이라도 괜찮아요. 하나씩 시작해 보세요.",
    stages: ["팬 인증", "예약 · 출석", "미션 참여", "선물 응모"],
    steps: [
      {
        label: "01  /  HOW TO JOIN",
        title: "나만의 팬 패스포트로\n첫 순간을 남겨요.",
        body: "엘리나 퀴즈로 팬 인증을 마치면\nFan Passport가 생겨요.\n예약과 미션은 이 패스포트로 시작해요.",
        actions: ["팬 인증하기"],
      },
      {
        label: "02  /  HOW TO JOIN",
        title: "만날 시간을 예약하고,\n코드로 출석해요.",
        body: "보고 싶은 LIVE를 미리 예약하세요.\nLIVE에서 안내하는 코드를 입력하면\n함께한 순간이 내 기록에 남아요.",
        actions: ["LIVE 일정 보기", "코드 출석하기"],
        note: "엘리나 Passport가 필요해요.",
      },
      {
        label: "03  /  HOW TO JOIN",
        title: "참여할수록 쌓이는\n나의 팬 활동.",
        body: "LIVE 퀴즈부터 활동 인증까지.\n미션마다 참여 조건과 보상을 확인하고\n내가 할 수 있는 활동에 참여해 보세요.",
        actions: ["미션 살펴보기", "활동 인증 보기"],
        note: "출석이 필요한 미션만 먼저 출석해 주세요.\n응모권 지급 여부는 각 활동의 조건에 따라 달라요.",
      },
      {
        label: "04  /  YOUR CHOICE",
        title: "모은 응모권으로,\n갖고 싶은 선물에 응모해요.",
        body: "엘리나의 응모권으로 원하는 경품을 골라 보세요.\n응모할 수량을 확인하고 직접 응모하면 돼요.",
        actions: ["선물 고르기"],
        note: "응모권을 받는 것과 경품에 응모하는 것은 달라요.\n경품별 기간과 참여 조건을 확인해 주세요.",
      },
    ],
    liveCard: {
      title: "엘리나와 함께하는 LIVE",
      flow: "일정 확인  →  예약  →  코드 출석",
      code: "LIVE에서 받은 출석 코드",
    },
    missionCards: [
      ["LIVE 미션", "퀴즈 · 설문에 참여하기"],
      ["활동 인증", "멤버십 · 티켓 · 현장 기록"],
    ],
    historyTitle: "함께한 순간은 MY에 차곡차곡.",
    historyBody: "내 패스포트, 예약한 LIVE와 응모 내역을 확인하세요.",
    historyAction: "내 기록 보기",
    faqTitle: "시작하기 전에, 궁금한 것들",
    faqs: [
      ["처음부터 로그인이 필요한가요?", "안내는 바로 볼 수 있어요. 팬 인증과 참여를 시작할 때 로그인해 주세요."],
      ["좋아요를 누르면 응모권을 받나요?", "좋아요에는 응모권이 지급되지 않아요. 활동별 보상 조건을 확인해 주세요."],
      ["모든 미션에 출석이 필요한가요?", "출석이 필요한 미션에서만 먼저 출석하면 돼요."],
      ["다른 최애의 응모권도 쓸 수 있나요?", "해당 셀럽의 응모권으로 응모해요. 엘리나 경품에는 엘리나 응모권을 사용해 주세요."],
    ],
    closingTitle: "엘리나와 함께할 첫 순간,\n지금 시작해 볼까요?",
    closingAction: "팬 인증하기",
    footer: "ByUs. Your Bias.    ·    한국어 / EN",
    imageAlt: "바다를 배경으로 선 엘리나",
    prizeAlt: "전시 공간에 걸린 작품을 바라보는 관람객",
  },
  en: {
    heroTitle: "Turn your fandom\ninto shared moments.",
    heroDescription:
      "Your ByUs guide with Elina.\nFrom fan verification to LIVE events,\nmissions and prize entries.",
    howToJoin: "How to join",
    viewPrizes: "View prizes",
    heroNote: "New here? Start with one small step.",
    stages: ["Fan verification", "Reserve · Check in", "Missions", "Prize entries"],
    steps: [
      {
        label: "01  /  HOW TO JOIN",
        title: "Your first moment.\nYour Fan Passport.",
        body: "Complete Elina’s fan quiz to get your Fan Passport. Use it to start reserving LIVE events and joining missions.",
        actions: ["Verify your fandom"],
      },
      {
        label: "02  /  HOW TO JOIN",
        title: "Save your spot.\nBe part of the moment.",
        body: "Reserve a LIVE you want to join. Enter the code shared during the LIVE to add that moment to your history.",
        actions: ["Explore LIVE events", "Check in with a code"],
        note: "An Elina Passport is required.",
      },
      {
        label: "03  /  HOW TO JOIN",
        title: "More ways to join.\nMore moments to keep.",
        body: "From LIVE quizzes to fan activity verification, find a mission for you. Check its requirements and rewards before joining.",
        actions: ["Explore missions", "View fan activity"],
        note: "Check in first only when a mission requires it. Raffle ticket rewards depend on each activity’s conditions.",
      },
      {
        label: "04  /  YOUR CHOICE",
        title: "Your tickets.\nYour choice of prize.",
        body: "Choose a prize and use your Elina raffle tickets to enter. Review the number of tickets before confirming.",
        actions: ["Choose a prize"],
        note: "Earning tickets does not enter you automatically. Check each prize’s entry period and requirements.",
      },
    ],
    liveCard: {
      title: "LIVE with Elina",
      flow: "Explore  →  Reserve  →  Check in",
      code: "Your check-in code from the LIVE",
    },
    missionCards: [
      ["LIVE missions", "Take quizzes and surveys"],
      ["Fan activity", "Memberships, tickets and moments"],
    ],
    historyTitle: "Your shared moments, saved in MY.",
    historyBody: "Find your Passport, reserved LIVE events and prize entries.",
    historyAction: "View my history",
    faqTitle: "Before you get started",
    faqs: [
      ["Do I need to sign in first?", "Read the guide without signing in. Sign in when you are ready to verify your fandom or join an activity."],
      ["Do likes earn raffle tickets?", "Likes do not earn raffle tickets. Check the reward conditions for each activity."],
      ["Does every mission require check-in?", "Check in first only when the mission requires it."],
      ["Can I use another creator’s tickets?", "Use tickets for the creator running the raffle. Elina prizes require Elina raffle tickets."],
    ],
    closingTitle: "Ready for your first\nmoment with Elina?",
    closingAction: "Verify your fandom",
    footer: "ByUs. Your Bias.    ·    KO / English",
    imageAlt: "Elina standing by the sea",
    prizeAlt: "A visitor viewing artwork in an exhibition space",
  },
} as const;
